### ISSUE TITLE
Method executeQuery is undefined

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb-java-driver#101]
Hi,
I am using 3.1.0 Arangodb java driver and 3.1 Arangodb. 

package org.formcept.arangodb;

import com.arangodb.ArangoConfigure;
import com.arangodb.ArangoDriver;
import com.arangodb.ArangoHost;
import com.arangodb.entity.CursorEntity;
import com.arangodb.entity.PlainEdgeEntity;

public class queryAQL {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ArangoConfigure configure = new ArangoConfigure();
		ArangoHost hostObj = new ArangoHost("127.0.0.1", 8529);
		configure.setArangoHost(hostObj);
		configure.setUser("root");
		configure.setPassword("12yuvi12");
		configure.init();
		ArangoDriver arangoDriver = new ArangoDriver(configure);
		String dbName = "test";
		String edge="meetupedges";
		String graphname="meetup_graph";
		arangoDriver.setDefaultDatabase(dbName); 
		String query = "for i in GRAPH_EDGES('meetup_graph', null) return i";
		CursorEntity<PlainEdgeEntity> result = arangoDriver.executeQuery(query, null, PlainEdgeEntity.class, true, 10);
		System.out.println("The graph has " + result.getCount() + " edges.");

	}

}
I am getting the following error 
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method executeQuery(String, null, Class<PlainEdgeEntity>, boolean, int) is undefined for the type ArangoDriver

	at org.formcept.arangodb.queryAQL.main(queryAQL.java:28)

**Comment by mpv1989** [comment]
Hi,
the method `executeQuery` was removed in driver version 3.0.x. You could use `executeDocumentQuery` instead.

```
AqlQueryOptions options = new AqlQueryOptions();
options.setBatchSize(10);
options.setCount(true);
DocumentCursor<PlainEdgeEntity> result = arangoDriver.executeDocumentQuery(query, null, options, PlainEdgeEntity.class);
```

With ArangoDB 3.1 we also overhaul our java driver ([blogpost](https://www.arangodb.com/2016/10/updated-java-drivers-with-arangodb-3-1/)) (current version 4.1.8). You should really take a look at it. We don't know how long we will support the old versions.

**Comment by ahr12** [comment]
Hello,
I try to use Java-Driver 4.1.8 but some libraries are miss like-
import com.arangodb.ArangoConfigure;
import com.arangodb.ArangoDriver;
import com.arangodb.ArangoException;
import com.arangodb.ArangoHost;
import com.arangodb.entity.EdgeDefinitionEntity;

Please fix this issue

**Comment by mpv1989** [comment]
Hi,
these classes don't exist anymore in the new driver.
[Here](https://github.com/arangodb/arangodb-java-driver#learn-more) you can find our documentation, JavaDoc, examples and a tutorial for our new java driver.
