### ISSUE TITLE
AQL result as JSON

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb-java-driver#102]
Is it possible to get a query result as plain json? I want to send the result without any changes to my js client. Therefor I want to save some extra serialization and deserialization.

**Comment by mpv1989** [comment]
Hi,
you can use `String` for the parameter `type` in method `query(query, bindVars, options, type)`. This will return you a `ArangoCursor<String>` which includes your results as json. If you want one big json-array with all results you have to iterate over ArangoCursor and build it yourself.


```
ArangoDB arangoDB = new ArangoDB.Builder().build();
ArangoCursor<String> cursor = arangoDB.db().query("your query", bindVars, options, String.class);
```
You can also find some examples [here](https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/example/graph/AQLActorsAndMoviesExample.java).

Best
Mark

**Comment by konsultaner** [comment]
Thank you that help me a lot!
