### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by normanuber** [arangodb/arangodb-java-driver#103]
Since the latest version is 4.x using a binary protocol and like most other binary clients, official support for connection pooling is a good feature. This will help with multi threaded web applications where a response is needed from the server (sync).

**Comment by mpv1989** [comment]
Yes, we also see it that way. It's on our todo-list but probably not before the next minor release of ArangoDB (3.2.x)

**Comment by mpv1989** [comment]
Implemented connection pooling. It will be available in version `4.1.11` and is already available `4.1.11-SNAPSHOT`.

See [here ](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/setup.md#connection-pooling) how to set the maximum number of connections.

**Comment by mpv1989** [comment]
version `4.1.11` is now available
