### ISSUE TITLE
ArangoVertexCollection delete multiple vertex

### ISSUE THREAD

**Issue by welovelain** [arangodb/arangodb-java-driver#106]
Is there a possibility to delete multiple Vertex?
Like in ArangoCollection class there is "deleteDocuments" method.
I don't use ArangoCollection as I need edges of vertexes to remove automatically.

**Comment by mpv1989** [comment]
Currently we don't support multi-vertex/edge operations. But we plan this for a future release (ArangoDB 3.x).

**Comment by welovelain** [comment]
Okay, I'll look forward to it.
By the way, if document not found by arangoCollection.getDocument it returns null. But if ArangoVertexCollection is used, then the exception is thrown. Is this a desired behavior?

**Comment by mpv1989** [comment]
Oh, no not really. Thanks for reporting. I will fix this.

Thanks & best
Mark

**Comment by mpv1989** [comment]
fixed in version `4.1.10`
