### ISSUE TITLE
ArangoDB 3.1.11 cluster crashes under heavy load 

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#107]
I posted this issue here: https://github.com/arangodb/arangodb/issues/2329

It contains how I am running arango cluster along with logs and snipet of java ingestion code.  I am not sure if it is an issue with the Java driver or the cluster itself.

**Comment by mpv1989** [comment]
looks like it doesn't belong to the driver. I will reopen this issue if needed
