### ISSUE TITLE
Object with _id and _key fields

### ISSUE THREAD

**Issue by mrbatista** [arangodb/arangodb-java-driver#11]
I have this situation:
```java
public class User {
  private String email;
  private String name;
  private String surname;
  private String username;
  private String password;

 /* getter and setter*/
}

/* ------- */
public T getByUniqueKey(String key, Object value) throws ArangoException {
String query = "FOR t IN " + getCollectionName() + " FILTER t." + key + " == @" + key + " RETURN t";
Map<String, Object> bindVars = new MapBuilder().put(key, value).get();
  return getConnection().executeQuery(query,
    bindVars, clazz, false, 0).getUniqueResult();
  }
/* ------ */
```
After calling the getByUniqueKey method, I would do like update  the `User` object.
I cannot use the `updateDocument` method because I do not have the _id field. In fact,
`_id` and `_key` fields are available only when call method that returns `DocumentEntity<T>` or extends `BaseDocument` class.
If extends `BaseDocument` other fields like `properties` are serialized and saved to DB.
I've used recently [this](https://github.com/triAGENS/arangodb-objectmapper) object mapper where each class extends `ArangoDbDocument`.
I could use this approach, however, would be redundant if the same class is used in a method that returns a `DocumentEntity<T>`

Any suggestions?

**Comment by mrbatista** [comment]
@a-brandt would be appropriate to add an example of how to update the objects returned by a AQL query. At the moment if extends `BaseDocument` the field properties is saved in the DB and other fields like `errorNumber`, `statusCode`, `code`, `unauthorized`, ecc... will be included in the deserialization of the object.
I await your own feedback.
Thanks

**Comment by a-brandt** [comment]
Hello mrbatista,

you can change your User class:
```
public static class User {
  @SerializedName("_id")
  String documentHandle;
  @SerializedName("_key")
  String documentKey;
  @SerializedName("_rev")
  long documentRevision;
  private String email;
  private String name;
  private String surname;
  private String username;
  private String password;
  /* getter and setter*/
}
```

**Comment by mrbatista** [comment]
I thought there was another way, since the methods create, update and delete return an object of type `DocumentEntity<T>` which contains the necessary fields.

**Comment by a-brandt** [comment]
I think we need a kind of ```executeDocumentQuery(...)``` that returns a ```DocumentCursorEntity<T>``` and the elements of the cursor are of type ```DocumentEntity<T>```.

**Comment by mrbatista** [comment]
Yes! would also `executeEdgeQuery(...)` that returns a `EdgeCursorEntity<T>` with elements are of type EdgeEntity<T>.
In many cases the acquisition of Document or Edge objects is done through an AQL query, for example in my case, check whether there is a person with a specific email address.

**Comment by a-brandt** [comment]
* added new cursor implementation for AQL queries
    * DocumentCursor<T> executeDocumentQuery(...)
* added new cursor implementation for simple queries
    * DocumentCursor<T> executeSimpleAllDocuments(...)
    * DocumentCursor<T> executeSimpleByExampleDocuments(...)
    * DocumentCursor<T> executeSimpleRangeWithDocuments(...)
    * DocumentCursor<T> executeSimpleFulltextWithDocuments(...)

**Comment by mrbatista** [comment]
Good job!
