### ISSUE TITLE
Please support HTTP protocol in 4.x

### ISSUE THREAD

**Issue by wenerme** [arangodb/arangodb-java-driver#111]
By user http protocol we can use expose one port in our server, java client can works with nginx reverse proxy like arangosh do.

It's not easy to expose a tcp port in server, so please support HTTP protocol, also with http we can easily add transparent ssl support.

Maybe arangodb should support websoket, then streaming and http can works together.

**Comment by mpv1989** [comment]
I understand your point of view. I will discuss your concerns with some colleagues.

**Comment by mpv1989** [comment]
@wenerme  we implemented the possibility to change the network protocol to HTTP in driver version 4.2.0. Take a look [here](https://github.com/arangodb/arangodb-java-driver#network-protocol) how to configure it.
