### ISSUE TITLE
Connectivity check operation

### ISSUE THREAD

**Issue by wenerme** [arangodb/arangodb-java-driver#114]
After build a db instance , there is no guarantee that the configuration is correct, I try to use `db.getVersion()` as Ping method,  but the user don't have the permission, is this require `_system` access ?

And why these operation need `_system` access ?

```
db.getVersion()
db.getAccessibleDatabases()
db.getLogLevel()
db.getUser(properties.getUser()) // Current user

Give me
Response: 401, Error: 11 - not authorized to execute this request
```

PS: driver version 4.1.10, server version 3.1

**Comment by mpv1989** [comment]
Yes, generally every db call needs a database as context. The db calls in the class `ArangoDB` requires  the database `_system` and therefore also a user with permissions to that database.

**Comment by wenerme** [comment]
So, how can I know which db is accessible by current user ? How to check am I admin user(by access _system ?) ? How to check the connectivity ?

**Comment by mpv1989** [comment]
To check which dbs are accessible by current user you could make a new connection with a separate user (which has permissions to `_system`) and call `ArangoDB.getAccessibleDatabasesFor(properties.getUser())`.

To check connectivity with a user which hasn't permissions to `_system` in case you now a db which he has permissions to, you could call `ArangoDB.db("<db-name>").getInfo()`.

**Comment by wenerme** [comment]
If user can access `_system`, then user become a `root` user ?

**Comment by mpv1989** [comment]
If a user has access to `_system` he can change the user permissions and therefore he can give himself access to every other database or simple to `*` which means access to all databases. So yes, a user with access to `_system` is a `root` user.

**Comment by wenerme** [comment]
That's the problem, non-root user is limited too much, so, dose arangodb suggest to use root user everywhere ?

**Comment by mpv1989** [comment]
I talked with a colleague about that. There was a misunderstanding of our docu on my side. It is indeed possible to call getVersion or getAccessibleDatabases on another database than `_system` within our HTTP api. I will changes this in the java driver today.

**Comment by mpv1989** [comment]
I added the methods `getVersion()` and `getAccessibleDatabases()` in the class `ArangoDatabase` in version `4.1.11-SNAPsHOT`. I will release version `4.1.11` within this week.

Usage:
```
ArangoDB db = new ArangoDB.Builder().build();
db.db("myDB").getVersion();
```
You still have to know at least one database the current user has access to.

**Comment by wenerme** [comment]
It's better than nothing, I already config a  database for current user, I will treat the `getVersion()` as the cheapest connection check operation.

**Comment by mpv1989** [comment]
version `4.1.11` is now available

it includes the methods `getVersion()` and `getAccessibleDatabases()` in the class `ArangoDatabase`
