### ISSUE TITLE
Reusing cursor/Limited cursor API?

### ISSUE THREAD

**Issue by sheinbergon** [arangodb/arangodb-java-driver#116]
Overviewing the driver's source code, it seems the ```query()``` method endpoint used for execution AQL queries is cursor aware/ready and uses the same params as descibed in [here](https://docs.arangodb.com/3.1/HTTP/AqlQueryCursor/AccessingCursors.html#create-cursor)

That's really good, expect from the fact I don't really see a method of reusing the cursor outside of the same query context - meaning, getting the first result set, extracting the cursor id, saving it somewhere and then re-passing it to the arangodb driver via some other method ( or even ```AqlQueryOption``` in order to get the next result set.

Am I missing anything? I think not having this functionality completely misses the point of having cursors.

**Comment by mpv1989** [comment]
Thanks for the feedback.
I implemented the method `ArangoDatabase.cursor(String, Class<T>):ArangoCursor<T>`.

**Comment by sheinbergon** [comment]
Thank you so much :)
