### ISSUE TITLE
New feature request. Auto reconnection and allow multiple specifying of multiple ips and ports.

### ISSUE THREAD

**Issue by yammelvin** [arangodb/arangodb-java-driver#12]
I would like to request for the following features to be implemented in the driver:

1. Auto reconnection when connection breaks.

2. Allow specifying of multiple ips and ports or server endpoints.

The above 2 will enable the driver to automatically connects to another coordinator when the coordinator it is connected to fails.

Even if you use a HA load balancer, when the primary load balancer fails and the secondary takes over with the same IP, the driver will require to reconnect to that IP address.

**Comment by a-brandt** [comment]
Hello yammelvin,

I added auto reconnection and fallback servers to the configuration class.

Example:
```
ArangoConfigure configure = new ArangoConfigure();
// default host
configure.setArangoHost(new ArangoHost("192.168.182.50", 8888));
// fallback server
configure.addFallbackArangoHost(new ArangoHost("192.168.182.50", 8889));
// number of connect retries (0 means infinite)
configure.setConnectRetryCount(1000);
// wait time for a connect retry 0.5 seconds
configure.setConnectRetryWait(500);

configure.init();
```
