### ISSUE TITLE
Why additional/unused entries in bindVars is not allowed?

### ISSUE THREAD

**Issue by FuweiChin** [arangodb/arangodb-java-driver#120]
**Situation:**
I have a `query` with one placeholder(@uid), while `bindVars` contains additional entries(username=Foo, fullName=Foo Bar).  

**Result:**
> com.arangodb.ArangoDBException: Response: 400, Error: 1552 - bind parameter 'username' was not declared in the query (while parsing)

says arangodb-java-driver 4.1.12

**Expectation:**
The driver should not raise any exception if additional entries in `bindVars` is provided, such that I can use bean-to-map converter to convert a `Bean` into a `Map<String,Object>`, and use the map as `bindVars`.

**Comment by mpv1989** [comment]
The Java driver is only mean as a low level driver which just uses the HTTP API and should not provide any deep logic.

ArangoDB itself does not allow unused bind parameters (see [docs](https://docs.arangodb.com/3.1/AQL/Fundamentals/BindParameters.html)).
> Bind parameters that are declared in the query must also be passed a parameter value, or the query will fail. Specifying parameters that are not declared in the query will result in an error too.
