### ISSUE TITLE
Unable to connect to Arango Db using Java

### ISSUE THREAD

**Issue by Priya1304** [arangodb/arangodb-java-driver#123]
Hi, I am trying to create connection in Arango Db using Java , IDE- Eclipse, as given in the official tutorial but after executing the program I am getting the exception "Unauthorized". I have logged in to Arango database using user name - root

Eclipse:
![image](https://cloud.githubusercontent.com/assets/7492304/26045285/d8909a5c-398c-11e7-92f0-427562f85049.png)

Login to Arango Db
![image](https://cloud.githubusercontent.com/assets/7492304/26045366/34f7c1b2-398d-11e7-9af3-7717d3249e89.png)

**Comment by mpv1989** [comment]
You have to set the user and password (default user "root", password empty):
```
ArangoConfigure configure = new ArangoConfigure();
configure.init();
configure.setUser("root");
configure.setPassword("");
ArangoDriver arangoDriver = new ArangoDriver(configure);
```

In addition I highly suggest you to update to our new java driver (version `4.1.12`). Which comes with a new API and a better performance). We also provide a tutorial for it (see [here](https://www.arangodb.com/tutorials/tutorial-sync-java-driver/))

**Comment by Priya1304** [comment]
Thanks for the instant reply. I will surely update to the higher version. I added the above two lines to my code, still facing the same issue. Do i need to explicitly use something else or start the database or write some command on arango shell 

![image](https://cloud.githubusercontent.com/assets/7492304/26058130/cfd4c9d2-39bf-11e7-8231-f6a31c68b986.png)

**Comment by mpv1989** [comment]
You just need to set the user "root" with the password you choose when installing arangodb.
When don't using the root user make sure your user has permissions to create a database.

**Comment by Priya1304** [comment]
It worked .. Thanks !!
