### ISSUE TITLE
expose keyMapAdapters to  ArangoDBAsync.Builder

### ISSUE THREAD

**Issue by sheinbergon** [arangodb/arangodb-java-driver#124]
keyMapAdapters basically allows the code to use custom types as map keys. Looking at the source code it currently supports primitive boxed types, but trying  to use custom type fails.

If we could configure the adapters map just like we register de/serializers,  It'd be great.

**Comment by mpv1989** [comment]
Thanks for the input.
I implemented it in the java-velocypack repo ([commit](https://github.com/arangodb/java-velocypack/commit/032904ba82de9e3d904cbd2e9cddbea3669d8173)).

I am currently working on driver version 4.2.0 which will include this change.

**Comment by sheinbergon** [comment]
Note that there is also a major issue related to this feature. 
Currently, the only workaround this is to register a VPackDeserializer  of type Map<KEY,VALUE>
or( Map[KEY,VALUE] ). However, due to the JVM's type-reasure or/and how your current code works, Registering more then one of these VPackDeserializer instances causes them to override one another.

**Comment by sheinbergon** [comment]
This seemed like an invalid List/Map type issue in the Scala module . I Create this PR - 
https://github.com/arangodb/java-velocypack-module-scala/pull/1
Please verify and let me know

**Comment by mpv1989** [comment]
4.2.0 is released
