### ISSUE TITLE
Transaction error message is swallowed

### ISSUE THREAD

**Issue by dchrzascik** [arangodb/arangodb-java-driver#125]
When executing transaction from sync driver exception message (in case of transaction failure) gets lost.

As an example consider following code snippet: https://gist.github.com/dchrzascik/129b7310ae6221b4886d76cd10e3d6f9
ArangoDBException contains only "Response: 500, Error: 500 - internal server error" message.

When invoking transaction through HTTP API, such error is passed:
POST http://localhost:8529/_db/structure/_api/transaction
Request:

{ 
  "collections" : { 
    "write" : "nodes"
  },
  "action" : "function (params) { throw 'My Error context' }"
}
Response:

{
  "exception": "My Error context",
  "error": true,
  "code": 500,
  "errorNum": 500,
  "errorMessage": "internal server error"
}

**Comment by mpv1989** [comment]
fixed in version 4.2.0, thanks again for your PR
