### ISSUE TITLE
VPack serialization ignores null fields

### ISSUE THREAD

**Issue by dchrzascik** [arangodb/arangodb-java-driver#127]
Currently serialization ignore all null fields. There are cases, however, when such nulls are beneficial. For instance, I have a transaction that takes parameters that are used to find items by example: let's say that all documents that don't have set a given field. Due to current implementation of VPack, this will result in ignoring that parameter and returning all items in database.

Consider following example:
<pre>
package com.example;

import java.util.HashMap;
import java.util.List;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import com.arangodb.ArangoDB;
import com.arangodb.ArangoDatabase;
import com.arangodb.entity.BaseDocument;
import com.arangodb.model.TransactionOptions;

public class VPackSerializationTest {

    public static final String DB_NAME = "testDB";

    public static final String COLLECTION = "items";

    private ArangoDB arangoDB;

    private ArangoDatabase database;

    @Before
    public void setUp() {
        arangoDB = new ArangoDB.Builder().build();

        arangoDB.createDatabase(DB_NAME);
        database = arangoDB.db(DB_NAME);
        database.createCollection(COLLECTION);

        HashMap<String, Object> params = new HashMap<>();
        params.put("color", "blue");

        database.collection(COLLECTION).insertDocument(new BaseDocument(params));
        database.collection(COLLECTION).insertDocument(new BaseDocument());
    }

    @After
    public void tearDown() {
        arangoDB.db(DB_NAME).drop();
    }

    @Test
    public void shouldFilterItemByExample() {
        final String action = "function myFunction(params) { "
                + "console.log(params);" // this prints {}, not {"color" : null} as expected
                + "var db = require('@arangodb').db; "
                + "return db._collection('items').byExample(params.example).toArray();"
                + "}";

        // I want all items that have color set to null or doesn't have color at all
        HashMap<String, String> example = new HashMap<>();
        example.put("color", null);

        HashMap<String, Object> params = new HashMap<>();
        params.put("example", example);

        final TransactionOptions options = new TransactionOptions()
                .allowImplicit(true)
                .params(params);

        List result = database.transaction(action, List.class, options);
        Assert.assertEquals(1, result.size());
    }

}
</pre>

**Comment by mpv1989** [comment]
Generally ignoring all null fields is important in the driver because of all the additional options for diverse API calls, like `TransactionOptions`. If we serialize every null field, we have to serialize field like `waitForSync` which then has to be of type `boolean` and this require a default value on driver/client side which we don't want.

In your case you can serialize `params` with null fields before putting it into `TransactionOptions`. The driver then does not serialize `params` again when it serializes `TransactionOptions`
```
TransactionOptions options = new TransactionOptions().allowImplicit(true).params(database.util().serialize(params, true));
```

**Comment by dchrzascik** [comment]
Ok, I understand such design choice to serialization. In that case, this is not an issue then.
