### ISSUE TITLE
404 javadoc

### ISSUE THREAD

**Issue by welovelain** [arangodb/arangodb-java-driver#128]
http://arangodb.github.io/arangodb-java-driver/javadoc-4_1/com/arangodb/util/ArangoSerializer.html

http://arangodb.github.io/arangodb-java-driver/javadoc-4_1/com/arangodb/internal/util/ArangoSerializerImpl.html

http://arangodb.github.io/arangodb-java-driver/javadoc-4_1/com/arangodb/internal/util/ArangoUtilImpl.html

Maybe more

**Comment by mpv1989** [comment]
Thanks for reporting.
Updated javadoc.
