### ISSUE TITLE
Graph Snapshots

### ISSUE THREAD

**Issue by welovelain** [arangodb/arangodb-java-driver#129]
Using ArangoDB as EventStore I faced the need of regular snapshots. In ArangoDB, as far as I know, there is only 'arangodump' command. Is there a possibility to implement it in Java driver?

**Comment by mpv1989** [comment]
Arangodump writes data from your database directly to your hard drive. Which is fast even if you have a large dataset.
The Java driver is just a wrapper for our HTTP API, so it receives responses from the server. Depending on size of your database this could be a response of multiple GB or even TB which is obviously not a good idea.

I suggest you to use arangodump locally on you machine and write a little script which executes it in regular time intervals.

**Comment by welovelain** [comment]
Got it, thanks.
