### ISSUE TITLE
Get all query results

### ISSUE THREAD

**Issue by sbakiu** [arangodb/arangodb-java-driver#13]
I fail to understand how to get all results of a query without setting `batchSize` parameter to a particular value, for example in:  
```
arangoDriver.executeQuery(query, bindVars, clazz, calcCount, batchSize);
```
Is there a documentation for this, if so can please provide the link?

**Comment by a-brandt** [comment]
In Version 2.5.3 you have to use the ```executeQueryWithResultSet()``` function.

see https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/example/AqlAndDeprecatedCursorExample.java

For the next driver version I want to add some more examples.

**Comment by sbakiu** [comment]
For some reason I get `com.arangodb.ArangoException: org.apache.http.NoHttpResponseException: The target server failed to respond`. This behavior happens if I send a request after a 5-10 minutes pause. Did you notice this issue before?

**Comment by jsteemann** [comment]
Maybe this is a timeout issue. The server has a default timeout for KeepAlive connections of 300 seconds. If a connection to the server was established but idle for 300 or more seconds, the server may close it. At the moment I am not sure if the Java driver will reconnect in this case. If not, does increasing the server-side timeout help? The configuration parameter for arangod is `--server.keep-alive-timeout`.

**Comment by sbakiu** [comment]
I don't think increasing the timeout would help. Is there any way to make sure the connection is open?

**Comment by a-brandt** [comment]
What kind of request do you make? Is it a simple document request or a query (or cursor) request?

Can you try the new 2.5.4 version?

**Comment by sbakiu** [comment]
I am just doing document requests insert/update or a query request. I will try the new version today :)

**Comment by sbakiu** [comment]
The new driver version solves the issue :+1:
