### ISSUE TITLE
Connection issues cannot be distinguished from document missing

### ISSUE THREAD

**Issue by tperamaki** [arangodb/arangodb-java-driver#133]
In `ArangoCollection.java` both the `documentExists(key)` or the `getDocument(key, type)` consume the errors, which makes it impossible to know if the document actually did not exist, or if there was a connection issue and we should try again later when the connectivity has been restored.

For example `arangoDB.db("database").collection("collection").documentExists("document")` returns true if the document exists, but false for everything else, which includes document does not exist, database does not exist, collection does not exist, and any connection issues.

**Comment by mpv1989** [comment]
@tperamaki Hi, thanks for reporting.

**Comment by mpv1989** [comment]
@tperamaki I saw your PR a little to late :-(

My solution is a bit different, but we can go with yours if you like.

**Comment by mpv1989** [comment]
@tperamaki I took a closer look into your solution. I think - especially with documentExists - some people will run into trouble because it isn't compatible any more.

I added a field in `DocumentExistsOptions` and `DocumentReadOptions` where you can define whether the exception should be catched or not.

**Comment by tperamaki** [comment]
Took a quick look into your commit, and I was wondering that shouldn't it still be returning false / null for cases where the error code is 404, as that basically means that everything went fine, but the document was not found?

**Comment by mpv1989** [comment]
good point. I will add a check on the response code like in your commit.

Thanks again
