### ISSUE TITLE
Negative BigDecimal being serialized incorrectly

### ISSUE THREAD

**Issue by lorling88** [arangodb/arangodb-java-driver#135]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [x] Windows, version: 8.1

I'm issuing AQL via:
- [x] this Driver: Latest

Hi,

I have been having this issue and need help to solve it.
I have a attribute stored as negative number for example "value": -359

When i retrieve this value out storing into a BigDecimal variable, the BigDecimal variable will be stored as 65177 instead of the original value -359.

A few other discoveries made:
1) changing the value to -359.1 will retrieve the BigDecimal variable correctly.
2) changing the value to -359.0 will become 65177
3) changing the value to 359 will retrieve as 359
4) changing the value to -9999 will become 55537

Somehow the negative value without decimal points are causing the issue.
The driver will take 65536 and deduct the negative BigDecimal figure and return the result.

Sample Codes:

public class myobject extends BaseDocument {
private BigDecimal value;
public setValue(BigDecimal value) { this.value = value; }
public getValue() { return this.value; }
}

Over at the Arangodb Driver class, get Document via Javabean style
database.collection("collection").getDocument(key, myobject.class);

Please kindly assist.
Thanks!

**Comment by mpv1989** [comment]
@lorling88 Hi, I wasn't able to reprocude your problem. I am using driver version `4.2.1` and used the following code.
```
public class BigDecimalTest {

  public static class MyObject extends BaseDocument {
    private BigDecimal value;

    public MyObject() {
      super();
    }

    public void setValue(final BigDecimal value) {
      this.value = value;
    }

    public BigDecimal getValue() {
      return this.value;
    }
  }

  private static final String COLLECTION = "collection";

  public static void main(final String[] args) {
    final ArangoDB arango = new ArangoDB.Builder().build();
    try {
      arango.db().createCollection(COLLECTION);

      final MyObject value = new MyObject();
      value.setValue(new BigDecimal(-359));
      final DocumentCreateEntity<MyObject> res = arango.db().collection(COLLECTION).insertDocument(value);

      final MyObject document = arango.db().collection(COLLECTION).getDocument(res.getKey(), MyObject.class);
      System.out.println(document.getValue());
    } finally {
      arango.db().collection(COLLECTION).drop();
    }
  }

}
```
the console output is `-359`
