### ISSUE TITLE
arangodump + arangorestore cast issue

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb-java-driver#136]
I used arangodump + arangorestore to restore a database on my server, however I am running into a cast issue with doubles:

```java
(Double) baseDocument.getAttribute(field);
```
which used to work, now gives:

```bash
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
```

**Comment by Queatz** [comment]
Worked around it by using `((Number) raw.getAttribute(field)).doubleValue()`.  I guess this is more of a `arangodump` and `arangorestore` issue not preserving type information on numbers.

**Comment by mpv1989** [comment]
@Queatz other than json - which only knows number - the storage format [VelocyPack](https://github.com/arangodb/velocypack/blob/master/VelocyPack.md) of arangodb differ between int and double. If your restored numbers aren't floating point numbers they were interpreted as int. The built in velocypack parser within the java driver parse these to long if you aren't using a bean which defines the value as double.

**Comment by Queatz** [comment]
Yeah, will close this issue, however there should be a warning somewhere that type information might get lost, since I was expecting my data to remain completely identical.
