### ISSUE TITLE
Getting "non-representable type" for _id i.e documentHandle

### ISSUE THREAD

**Issue by bathejaSanjay** [arangodb/arangodb-java-driver#137]
I am migrating from Arango 2.8 to 3.1 . Have backed up 2.8 data to 3.1 on my local. 
While using the "4.2.0" version java driver, I get a error "non-representable type" for _id i.e documentHandle for all my documents. I inspected the data by adding a debug point at "ArangoUtilImpl [line: 92] - deserialize(VPackSlice, Type)	" and data is:

`{"_id":"(non-representable type)","_key":"8350458430628","_rev":"_VTAwsYO--_","blockedBy":"User 2","blockedOn":"2017-07-13T17:27:44.692Z","blockedUser":"User 1","reason":"FRAUD"}`

The java bean does have a property with @DocumentField(Type.ID) annotation. 
Am I missing something?

**Comment by mpv1989** [comment]
@bathejaSanjay is the bean property annotated with `@DocumentField(Type.ID)` from type `String`?
Can you post your code with one of the driver calls which goes wrong?

**Comment by bathejaSanjay** [comment]
@mpv1989 Yes, the property is annotated with `@DocumentField(Type.ID)` from type `String`. 
I was facing this issue specifically with 4.2.0 version. I tried 4.1.8 and 4.2.1 , it is working as expected. The _id field is deserialized properly.

**Comment by zqiubol** [comment]
So the question is to upgrade the version?

**Comment by rashtao** [comment]
@zqiubol  
This issue is outdated and related to old versions. In case of problems, please open a new issue.
