### ISSUE TITLE
Missing support for custom visitor result in ArangoDatabase.executeTraversal()

### ISSUE THREAD

**Issue by mvollmary** [arangodb/arangodb-java-driver#138]
The result `TraversalEntity` from `executeTraversal()` does not support additional results when using a custom visitor.

See example in [docs](https://docs.arangodb.com/3.2/HTTP/Traversal/index.html#executes-a-traversal)
```
{ 
  "startVertex" : "persons/alice", 
  "graphName" : "knows_graph", 
  "direction" : "outbound", 
  "init" : "result.visited = 0; result.myVertices = [ ];", 
  "visitor" : "result.visited++; result.myVertices.push(vertex);" 
}
```
`myVertices` is returned but ignored when `TraversalEntity` is deserialized.

**Comment by rashtao** [comment]
Closing since the related API is now deprecated in favor of http://arangodb.github.io/arangodb-java-driver/javadoc-6_16/com/arangodb/ArangoDatabase.html#query-java.lang.String-com.arangodb.model.AqlQueryOptions-java.lang.Class-
