### ISSUE TITLE
More examples for Batch/Transaction/Action

### ISSUE THREAD

**Issue by terrybleger** [arangodb/arangodb-java-driver#14]
Is this driver support command for execute Batch, Transaction, and Action?

Would you consider to create examples for that?

Thanks.

**Comment by a-brandt** [comment]
I added an example for Transaction.

**Comment by zbutfly** [comment]
but where is the example?

**Comment by zbutfly** [comment]
but where is the example? @a-brandt

**Comment by mpv1989** [comment]
@zbutfly We have some [transaction tests](https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/ArangoDatabaseTest.java#L984-L1114) that should serve as examples
