### ISSUE TITLE
Request Max Connection Age / Max Connection Idle time

### ISSUE THREAD

**Issue by ldap4life** [arangodb/arangodb-java-driver#141]
Hello, it would be nice if connections in the pool could have a maximum lifetime set on them, and have them close when that time elapses. Similarly, it would be nice if they could have an idle time, and if they arent used within that idle time, they are closed. Thank you.

**Comment by mpv1989** [comment]
@ldap4life @Himansu-Nayak I will discuss this feature with the team on Monday. I see no reason not to implement it. I will keep you up-to-date.

**Comment by Himansu-Nayak** [comment]
thanks a million Mark @mpv1989

**Comment by ldap4life** [comment]
I was able to accomplish my needs by calling setValidateAfterInactivity on the connection manager in the http connection code. nb that only has an effect if youre using http as the protocol.

**Comment by Himansu-Nayak** [comment]
@ldap4life, unfortunately, we used velocity stream protocol from our spring boot app.

**Comment by mpv1989** [comment]
Hi @ldap4life and @Himansu-Nayak,

I implemented a TTL (time to life) for connections in version `4.3.7`. But until now I had not found the time to implement idle time for connections. I hope this first step will help you already.

Usage:
```java
ArangoDB arango = new ArangoDB.Builder().connectionTtl(milliseconds).build();
```

best
Mark

**Comment by Himansu-Nayak** [comment]
@mpv1989 @ldap4life Hi Mark we also use "arangodb-spring-data" which still points to an older version of the driver. Any hope when can we get the next release?

**Comment by mpv1989** [comment]
@Himansu-Nayak I will try to release version 2.1.0 of "arangodb-spring-data" today
