### ISSUE TITLE
updateVertex(vertexModel.key, vertexModel) does not update the revision

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb-java-driver#145]
The title says it all. I use the latest version of the java driver and experienced that the update method for vertexes does not change the revision in the model. My model extends an abstract model that has the key fields declared as follows:

``` 
    @DocumentField(DocumentField.Type.ID)
    protected String id;
    @DocumentField(DocumentField.Type.KEY)
    protected String key;
    @DocumentField(DocumentField.Type.REV)
    protected String revision;
    @DocumentField(DocumentField.Type.FROM)
    private String from;
    @DocumentField(DocumentField.Type.TO)
    private String to;
```

**Comment by mpv1989** [comment]
@konsultaner thanks for reporting. I fixed this in version 4.2.4 which I released today
