### ISSUE TITLE
Please add an api to check if collection exists.

### ISSUE THREAD

**Issue by rajeshdalai** [arangodb/arangodb-java-driver#146]

**Comment by mpv1989** [comment]
@rajeshdalai thanks for your feedback. I added a method `exists()` in `ArangoCollection`. You can already test it with version `4.2.5-SNAPSHOT.

**Comment by rajeshdalai** [comment]
Is there any efficient method to do this instead of iterating through the list of all collection names.

**Comment by mpv1989** [comment]
@rajeshdalai we could call `ArangoCollection.getInfo()` which throws an expection if the collection does not exists and return exists = false in that case.

**Comment by mpv1989** [comment]
I released version 4.2.5
