### ISSUE TITLE
Save inputstream without converting to bytearray?

### ISSUE THREAD

**Issue by publicocean0** [arangodb/arangodb-java-driver#148]
how can i save a file in orangodb ?
Is there a way for saving a inputstream in db without not converting in bytearray. Is there stream api?

**Comment by mpv1989** [comment]
@publicocean0 No, sry. Currently the only way to save a file is by using a bytearray or base64 encoded String.

**Comment by publicocean0** [comment]
sorry another question (i m new in arangodb). 
I looked a bit arangodb manual but it is not clear how to use index in a query.
considering i have 
a object saved in a table. The numbers of instances saved are very huge (a billion) 

A {
String name;
List<String> types
}

i need to create a query llike select * from (name="ab*" and types in "type1") or (type in type1, type2).


it is possible ? 

pratically the question is: i saw how to create a index in a field . Ok 
but in th case i want search in multiple fields in a big table how to do?

**Comment by mpv1989** [comment]
Except from the fulltext index you can define an index on multiple fields.

For questions I suggest you to use StackOverflow, [GoogleGroups](https://groups.google.com/forum/#!forum/arangodb) or our community [Slack](slack.arangodb.com). Github is not the right platform for this.

**Comment by grexe** [comment]
btw @publicocean0 "info" is not a very descriptive issue title, and it's called *A*rangoDB...

**Comment by publicocean0** [comment]
sorry for mistake in the name :)
