### ISSUE TITLE
Failed to execute query. Response: 400, Error: 1228 - error during validation of incoming VPack: Invalid UTF-8 sequence

### ISSUE THREAD

**Issue by frcmail** [arangodb/arangodb-java-driver#149]
Hi, I was using arangodb-java-driver 4.2.2 to query AQL with "for v in Dep filter v.Name=='咨询实施事业一部专家组' return v.Name"  .

code:
 ArangoCursor<BaseDocument> cursor = arangoDB.db(dbName).query(query, null, null,BaseDocument.class);

when i Execute string contains Chinese,it throws the exception below:

Failed to execute query. Response: 400, Error: 1228 - error during validation of incoming VPack: Invalid UTF-8 sequence

Any idea?

**Comment by mpv1989** [comment]
@frcmail I tested your query and also saved document with your filtered value and it worked for me. Are you sure you set your source-code encoding to utf-8?

Beside that your code can't work. Your query return `v.Name` which is a String but you set the return type in `query()` to `BaseDocument`.

**Comment by frcmail** [comment]
@mpv1989 all of my source-code encoding to utf-8,and it can't works for me. 
`			  query="for v in Dep filter v.Name=='研发中心成本管控产品部' return v.Name";
			  String query1 = query;
			try {
				query1 = new String(query.getBytes("UTF-8"),"UTF-8");
			} catch (UnsupportedEncodingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
//			  ArangoCursor<BaseDocument> cursor = arangoDB.db(dbName).query(query, null, null,BaseDocument.class);
			  ArangoCursor<String> cursor = arangoDB.db(dbName).query(query1, null, null,String.class);
			  System.out.println(cursor);`

can you show me the tested code?

**Comment by frcmail** [comment]
@mpv1989 all of my source-code encoding to utf-8,and it can't works for me.

`query="for v in Dep filter v.Name=='研发中心成本管控产品部' return v.Name";`
`String query1 = query;`
`query1 = new String(query.getBytes("UTF-8"),"UTF-8");`
`ArangoCursor<String> cursor = arangoDB.db(dbName).query(query1, null, null,String.class);`
`System.out.println(cursor);`

can you show me the tested code?

**Comment by frcmail** [comment]
oh,i find the solution,the Chinese string encode to "unicode" before execution
