### ISSUE TITLE
Jackson support

### ISSUE THREAD

**Issue by aponcon** [arangodb/arangodb-java-driver#15]
Hi,

Actually this library is using google-gson for managing JSON.
But what about Jackson? Some projects are already using Jackson instead of google.gson and have a complex configuration for serializing and deserializing data.

It could be very useful to let the user choose between Gson, Jackson or even another solution.

Is there any plan to add support to Jackson or another library?

**Comment by a-brandt** [comment]
Hi,

we have no plans add support for Jackson. (We have to improve ArangoDB support first)

**Comment by mrbatista** [comment]
+1

**Comment by sheinbergon** [comment]
Hi

Let me just start by saying your driver is pretty amazing. By far one of the best java  SDKs I've worked with.
However , Jackson support could be really useful. Would you be willing to receive a Pull Request If I'' write an integration ?

**Comment by mpv1989** [comment]
@aponcon @mrbatista @sheinbergon I implemented VelocyPack support for Jackson within [jackson-dataformat-velocypack](https://github.com/arangodb/jackson-dataformat-velocypack).

With driver version 4.5.2 you are able to use Jackson as an alternative serializer. Take a look into the [docs](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/Drivers/Java/Reference/Serialization.md#use-of-jackson-as-an-alternative-serializer) to see how easily it is set up.
