### ISSUE TITLE
Information on connection use across threads

### ISSUE THREAD

**Issue by beoliver** [arangodb/arangodb-java-driver#150]
in many of the examples calls are chained e.g. 
`arangoDB.db("myDatabase").collection("myCollection").updateDocuments(documents);`
But the same could obviously be achieved by storing references to the connection, database, collection etc, which would at least appear to have less overhead.

I am wondering if this approach, for example sharing a collection object between threads is unsafe?
Assuming a web server with m threads should there be only one "connection" and then chained method calls, or can there be one connection and n < m "database"/"collection" objects shared between the m threads?

As far as I can tell this information is not in the docs and would be useful to know.

**Comment by mpv1989** [comment]
I answered you on stackoverflow https://stackoverflow.com/questions/46533915/arangodb-java-driver-reuse-of-objects
