### ISSUE TITLE
provide a way to set ID of a document for better clone support

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb-java-driver#152]
The Java driver (using 4.1.12) only allows setting the `key`, but not the `id` of a document.

This is cumbersome in situations where I want to override a document in the DB but keeping the same ID and key, e.g. during a full update (avoiding having to override every single property).

I know it is possible to update a document that has a`NULL _id` and a `key`, then `db.collection(collectionName).updateDocument(baseObject.getKey(), baseObject, UPDATE_OPTIONS)` will work fine and take the ID from the key, as expected.

However this makes writing code for transparently `upserting` documents cumbersome, because in the case of a `clone` operation, I cannot follow the usual logic that a document without an `ID` does not exist and needs an `insert` - because the Java driver does not allow me to copy the ID of the old document in my clone - so I need a special case for that and implement the update myself, or else I run into a wrong `INSERT` and the driver of course fails because the document with that ID already exists.

Proposed solution:
* provide a method to set the ID in a document and/or
* provide a single `upsert` method that does the UPSERT logic we all know and love

**Comment by mpv1989** [comment]
@grexe  Thanks for your feedback.

I added a setter for id in `BaseDocument`. Currently we have no plans of implementing an `upsert` method because the driver should be low level but I will discuss this again with some colleagues.

I am currently replacing some json parsing stuff in the driver and planning a release at the end of this month.

**Comment by grexe** [comment]
Thanks @mpv1989 glad to hear and like the support here!
However I just discovered the method `replaceDocument` which seems to do exactly what I want, keep the ID  but replace the full document. Sorry I didn't notice this earlier.

**Comment by mpv1989** [comment]
I released version 4.2.5 which includes my changes on `BaseDocument`
