### ISSUE TITLE
Support to Apache TinkerPop API

### ISSUE THREAD

**Issue by otaviojava** [arangodb/arangodb-java-driver#154]
Hey,

Is there any plans to ArangoDB has support to Apache TinkerPop in the graph database?
http://tinkerpop.apache.org/

**Comment by jean-amana** [comment]
It would indeed be very useful.
This is a criteria for the adoption of ArangoDB in my company.

**Comment by dothebart** [comment]
closing as duplicate of https://github.com/arangodb/blueprints-arangodb-graph/issues/15
