### ISSUE TITLE
orphaned ExecutorService blocks normal application termination

### ISSUE THREAD

**Issue by rwe17** [arangodb/arangodb-java-driver#156]
I'm using the lastest version 4.1.4 of this driver project.
In our program, the ArangoDB is configured to use VelocyStream and a custom VPackModule, which i've configured using the ArangoDB.Builder.

The issue is, that after writing and reading Data to and from the database one active ExecutorService still remains in the JVM and prohibits the whole application for a clean termination, althought i've called ArangoDB.shutdown() at the end.

I've seen, that in the class Collection (line 136) an ExecutorService is created twice. One for operations like listing all graph names and the second when documents should be read from the database. The first ExecutorService is correctly shutdown due to the call ArangoDB.shutdown(), but the the second ExecutorService remains and causes that our program, or server will never end.

Please can you fix this in a new version or can describe a solution for this issue. Otherwise i have to switch back to an older 3.x version without supporting the Velocy conversion.

**Comment by mpv1989** [comment]
@rwe17 Thanks for reporting. I will take a look at it this week.

**Comment by mpv1989** [comment]
The latest version is `4.2.4`. Does the problem still occur with it?

**Comment by rwe17** [comment]
The version with the issue was 4.2.4. 
I few minutes ago, i've build the driver with your commit and tested it in our application. Your bugfix has solved my issue. Thank you very much for your quick response.

**Comment by mpv1989** [comment]
Ok great. I release version 4.2.5.
