### ISSUE TITLE
traversal error

### ISSUE THREAD

**Issue by weickdev** [arangodb/arangodb-java-driver#159]
It seems useless by setting the filter through traversal api:
```
...
options.filter("function myfilter(config, vertex, path){if(vertex.type == 1) return 'exclude'}");
...
TraversalEntity<BaseDocument, BaseEdgeDocument> result = arangoDB.db(dbName).executeTraversal(BaseDocument.class, BaseEdgeDocument.class, options);
...
```

it doesn't filter any vertex

**Comment by mpv1989** [comment]
@weickdev The `filter` only has to contain the function body.

`options.filter("if(vertex.type == 1) return 'exclude'");`

**Comment by weickdev** [comment]
@ it works, thank you! By the way, the document says there is a  'expandFilter' config, why the api does't have this config?

**Comment by mpv1989** [comment]
@weickdev The traversal API is kind of deprecated. We suggest to use AQL for graph traversals (see [here](https://docs.arangodb.com/3.2/AQL/Graphs/Traversals.html)). We don't spend any more time in developing the corresponding HTTP API.

**Comment by weickdev** [comment]
@mpv1989 But the traversal AQL can't do any filter during the traversal. If I want to filter some vertex or edge during the traversal, what should I do?

**Comment by weickdev** [comment]
@mpv1989 OK, I will try the AQL, Thank you!

**Comment by mpv1989** [comment]
@weickdev wish you much success. Feel free to join our [community slack](https://slack.arangodb.com/) where you can live chat with other members of our community or developers from ArangoDB. This is the best platform if you need any further help.
