### ISSUE TITLE
What is the difference between the three ways of linking? What should be the scene?

### ISSUE THREAD

**Issue by zhenruyan** [arangodb/arangodb-java-driver#161]
VST,
    HTTP_JSON,
    HTTP_VPACK;

**Comment by dothebart** [comment]
Hi, 
HTTP Json does classic json posting via the regular HTTP interface. This could be usefull for debugging & sniffing. 
HTTP VPACK uses the similar http interface as the json one, but transfairs data in the faster parseable and less chatty [velocypack](https://github.com/arangodb/velocypack) 
VST is Velocystream. It replaces http headers by similar velocypack objects and adds the possibility to send multiple requets through the same connection.

**Comment by zhenruyan** [comment]
How should the Max_connection parameter be set? The server sometimes has a link that does not release the problem that caused the link to be interrupted

**Comment by dothebart** [comment]
A quick search through https://github.com/arangodb/arangodb-java-driver/#connection-pooling says that the client libs come with sensefull defaults. 
You should be fine with one vst connection. 
What are you currently using? And what sort of issues did you run into? can you elaborate your situation with a bit more details? What are you doing, and whats happening?

**Comment by zhenruyan** [comment]
When there is a large number of links, occasionally there will be links can not be released

**Comment by mpv1989** [comment]
You could set a timeout for the connections with 
```
ArangoDB arango = new ArangoDB.Builder().timeout(30000).build();
```
