### ISSUE TITLE
Shouldn't ArangoEdgeCollection throw exception on invalid edges?

### ISSUE THREAD

**Issue by christian-lechner** [arangodb/arangodb-java-driver#164]
Hi!

Can you tell me the difference between `ArangoCollection.insertDocument()`, `ArangoVertexCollection.insertVertex()` and `ArangoEdgeCollection.insertEdge()`?

I thought that `ArangoVertexCollection` and `ArangoEdgeCollection` should perform additional checks. 

For example:
There is no difference when I insert an edge with `insertDocument()` and `insertEdge()`. Both check for a valid collection, but not if the source/target vertex is correct.

Is this intended behaviour? If yes, why should I even use the vertex/edge methods?

**Comment by mpv1989** [comment]
Hi,

`ArangoVertexCollection` and `ArangoEdgeCollection` can only be used on collections which are part of a named graph. Then - as you already assumed - additional checks are performed whether the source/target are valid.

If you don't need these checks I suggest using `ArangoCollection.insertDocument()` which is much faster.

For more information about named graphs take a look [here](https://docs.arangodb.com/3.2/Manual/Graphs/#named-graphs).

**Comment by christian-lechner** [comment]
My collections are part of a named graph.
I've created a small example, that illustrates the problem:
```java
public class MyEdge {
	public String _from = "source-collection/123";
	public String _to = "target-collection/123";
}
arango.db("mydb").graph("mygraph").edgeCollection("relationships").insertEdge(new MyEdge());
```
`source-collection/123` and `target-collection/123` do not exist. Shouldn't there be an exception?

**Comment by mpv1989** [comment]
There should be an exception when you use `insertEdge()` and your `_from` or `_to` does not exists. But even if you use a named graph you can use `insertDocument()` or any other method in `ArangoCollection` which then does not do any checks.

For example if you use `ArangoVertexCollection.deleteVertex()` in addition to the passed vertex all edges which have the vertex id in their `_from` or `_to` will be deleted. If you use `ArangoCollection.deleteDocument()` instead only the passed document will be deleted.

The named graph feature set is only used when you use the APIs `ArangoGraph`, `ArangoVertexCollection`, `ArangoEdgeCollection`.

**Comment by christian-lechner** [comment]
I think you didn't understand me correctly.

I AM USING `ArangoGraph`, `ArangoVertexCollection`, `ArangoEdgeCollection`. See above example:
`arango.db("mydb").graph("mygraph").edgeCollection("relationships")` returns `ArangoEdgeCollection`.

I use `insertEdge` of `ArangoEdgeCollection`, but there is NO EXCEPTION thrown, but there should be one.

**Comment by mpv1989** [comment]
Ok, that is a bug. I created an issue in our main repo (see [here](https://github.com/arangodb/arangodb/issues/3811)).

**Comment by christian-lechner** [comment]
Thanks Mark for your quick responses and help.

I thought that this might be an ArangoDB and not a driver issue, because the driver calls the correct endpoint `/_api/gharial/` which should check for valid edges.

**Comment by mpv1989** [comment]
I'll just clear up the repo a bit . We have open PRs ([devel](https://github.com/arangodb/arangodb/pull/4984) , [3.3](https://github.com/arangodb/arangodb/pull/4983), [3.2](https://github.com/arangodb/arangodb/pull/4993)) for this topic, so I close the issue here
