### ISSUE TITLE
ArangoCollection getDocument() variants are inconsistent

### ISSUE THREAD

**Issue by CuriusAlgo** [arangodb/arangodb-java-driver#168]
In `ArangoCollection.java`, `getDocument(key, type)` ignores all errors and returns null. `getDocument(key, type, options)` only returns null when the document does not exist and throws otherwise. That means, in the presence of connection issues, the first variant will return null, the second will throw (regardless of the actual options).

This seems to be an oversight from #133. `getDocument(key, type)` should be implemented by forwarding to `getDocument(key, type, options)` with default constructed options, just like `documentExists` does.

**Comment by mpv1989** [comment]
@CuriusAlgo Thanks for reporting

**Comment by mpv1989** [comment]
Fixed in version 4.3.3
