### ISSUE TITLE
Please add distributeShardsLike to CollectionCreateOptions

### ISSUE THREAD

**Issue by gabor-bata** [arangodb/arangodb-java-driver#170]
As per https://docs.arangodb.com/3.3/Manual/Graphs/Pregel/#requirements-for-collections-in-a-cluster-non-smart-graph, edge collections have to be sharded in a specific way, i.e. the `distributeShardsLike` have to be defined as well, but I could not found that in the Java driver.

Could you please add that option to the `CollectionCreateOptions` class?

**Comment by mpv1989** [comment]
@gabor-bata Thanks for reporting
Fixed in version 4.3.3
