### ISSUE TITLE
Sort paths

### ISSUE THREAD

**Issue by Miosota** [arangodb/arangodb-java-driver#175]
Hello! Please, can you explain me how i can sort paths. Now i have next code 

```
          TraversalOptions options = new TraversalOptions()
                    .edgeCollection("edges")
                    .startVertex("nodes/9149892904413851091")
                    .verticesUniqueness(TraversalOptions.UniquenessType.path)
                    .direction(TraversalOptions.Direction.any)
                    .strategy(TraversalOptions.Strategy.depthfirst)
                    .order(TraversalOptions.Order.preorder)
                    .minDepth(5)
                    .maxDepth(5);
            System.out.println("1");
            TraversalEntity<BaseDocument, BaseEdgeDocument> traversal = 
            db.executeTraversal(BaseDocument.class, BaseEdgeDocument.class, options);
```

How i understand .sort method in options will sort edges. But i wanna sort paths. Any ideas?

Thanks.

**Comment by goedderz** [comment]
Hi @Miosota,

by which criteria do you want to sort paths? Or even better, could you tell what you ultimately try to achieve (e.g., find a shortest path)? I'll try to give an example then.

On an organizational point, the issues in Github are used for bugtracking, not support. If its not too inconvenient for you, could you please post the question on StackOverflow instead? You can also post the link to the question here.

Kind regards

Tobias

**Comment by Miosota** [comment]
Hi , @goedderz ,
Sorry. Here is a link https://stackoverflow.com/questions/48800785/arangodb-java-driver-sort-paths

I want to test two cases: 
1. sort by length of paths  ( so I will find the shortest path)
2. sort by sum of relationships' weights   (so i will be able to find a path with the less weight)

**Comment by goedderz** [comment]
Thanks @Miosota,

I posted an answer on StackOverflow.

Kind regards

Tobias
