### ISSUE TITLE
ErrorEntity should be Serializable

### ISSUE THREAD

**Issue by haqer1** [arangodb/arangodb-java-driver#178]
ErrorEntity should be Serializable to avoid exceptions like the following in environments involving some remoting:
com.arangodb.ArangoDBException : Response: 409, Error: 1210 - unique constraint violated - in index 1355495 of type hash over ["email"]; conflicting key: 1355503 [Proxied because : Original exception caused: class java.io.NotSerializableException: com.arangodb.entity.ErrorEntity]

**Comment by mpv1989** [comment]
Thanks for the feedback. Change will be in the next release.
