### ISSUE TITLE
updateDocument / updateDocuments inconsistency

### ISSUE THREAD

**Issue by hepworthjd** [arangodb/arangodb-java-driver#180]
Hello,

I think there is an inconsistency with updateDocument and updateDocuments with regard to this - looking at the source for the former I see:

```
		request.setBody(
			util().serialize(values, new ArangoSerializer.Options().serializeNullValues(false).stringAsJson(true)));

```
compared to the latter:

```
		request.setBody(util().serialize(value, new ArangoSerializer.Options()
				.serializeNullValues(params.getSerializeNull() == null || params.getSerializeNull())));
```

This means I have to use multiple calls to updateDocument if I want null values removed

Thanks
Julian

**Comment by mpv1989** [comment]
Thanks for reporting. I pushed the fix, it will be included in 4.3.8 and can already been tested with 4.3.8-SNAPSHOT
