### ISSUE TITLE
can some variation of getDocument() be used with a unique index?

### ISSUE THREAD

**Issue by alexpmorris** [arangodb/arangodb-java-driver#182]
I'm trying to bring up a single document based on a unique field in a collection.  As such, I created a unique hash index based on that key.  Is there a way to use a method such as getDocument() to more directly access the document by referencing an indexed field *(in this case, a unique userid)*, or must I perform an AQL query in order to fetch a document based on an indexed field? 

Thanks kindly for your clarification on this.

**Comment by mpv1989** [comment]
Hi @alexpmorris,

the driver uses the REST API of ArangoDB which only supports fetching documents over their id/key. For your case you have to perform an AQL query.

best
Mark
