### ISSUE TITLE
Instant serialized in server-local timezone

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb-java-driver#187]
With the following model:

```java
class Model {
    public Instant time;
}

```

The serialized time saved in Arango is in server-local timezone.  So, when using it in a query, i.e. `x.time < DATE_NOW()` isn't predictable, since `x.time` is in server-local time, whereas `DATE_NOW()` is in UTC. 

Not sure if this is a feature request serialize Instants in UTC, or a bug.

**Comment by mpv1989** [comment]
This could be solved with arangodb/java-velocypack/issues/6

**Comment by mpv1989** [comment]
I just released version 4.4.0 of the driver and 1.1.0 of arangodb/java-velocypack-module-jdk8 which provides new serialization for `Instant` and other types of java.time.*
See corresponding [commit](https://github.com/arangodb/java-velocypack-module-jdk8/commit/014c07cb736aea6b2b0fd99fbea51fa9efccf411).

**Comment by Queatz** [comment]
Awesome, will give it a whirl!
