### ISSUE TITLE
createEdge returns "database not found" error

### ISSUE THREAD

**Issue by mikub** [arangodb/arangodb-java-driver#19]
Method *createEdge* takes *graphName* as a first argument - however this argument is in fact used as a **databaseName** during rest call URL construction. 
see *InternalEdgeDriverImpl* line 54:

    HttpResponseEntity response = httpManager.doPost(createEndpointUrl(graphName, "/_api/edge"), params, body);

However *createEndpointUrl* method takes following parameters:

    protected String createEndpointUrl(String database, Object... paths) throws ArangoException

Property *graphName* is here used as a database name (first argument) in the createEndpointUrl method call and will be placed in the generated URL that should have this format: 

    http://server:port/_db/<database-name>/_api/edge

Currently following URL is generated:

    http://server:port/_db/<graph-name>/_api/edge

which will always result in **404** and "database not found" error

**Comment by a-brandt** [comment]
I fixed the the function in 2.5.6-SNAPSHOT.
