### ISSUE TITLE
Support for exclusive write operations

### ISSUE THREAD

**Issue by harrigan** [arangodb/arangodb-java-driver#190]
Will support for exclusive write operations (https://github.com/arangodb/arangodb/pull/4091) be added to TransactionOptions?

**Comment by mpv1989** [comment]
@harrigan yes, as soon as the feature is implemented

**Comment by mpv1989** [comment]
@harrigan I added `TransactionOptions#exclusiveCollections(String[])` in version 4.6.0

best
Mark
