### ISSUE TITLE
4.3.7 changes: fixed DateUtil does incorrect conversion of UTC time

### ISSUE THREAD

**Issue by lorling88** [arangodb/arangodb-java-driver#191]
Hi,

I had updated to the latest driver 4.4.0 version from 4.3.4 and notice the timestamp serialized and deserialized has changed to be UTC timezone. Before this change, the time are following the local machine timezone. 

For example: before 4.4.0 the timestamp stored in database is 2018-01-01T18:00:00 (UTC+6)
after 4.4.0 the timestamp stored is 2018-01-01T12:00:00 (UTC)

I did some search and notice one of the change log on "4.3.7 saying fixed DateUtil does incorrect conversion of UTC time", could this be the cause?
My question is there anyway i can retain my timezone instead of storing UTC?
Please kindly advise.
Thanks!

**Comment by mpv1989** [comment]
Hi @lorling88,

fixing the behavior there was a discussion in this [issue](https://github.com/arangodb/spring-data/issues/36).
Like already in the issue mentioned you should use `LocalDate ` or `LocalDateTime` to store non UTC dates.

Don't forget to register the [JDK8 module](https://github.com/arangodb/java-velocypack-module-jdk8) in the driver instance.

best
Mark
