### ISSUE TITLE
How to use Pregel module function using arangodb-java-driver

### ISSUE THREAD

**Issue by dengwfxx** [arangodb/arangodb-java-driver#195]
How to use Pregel module function using arangodb-java-driver

**Comment by mpv1989** [comment]
@dengwfxx The REST API for pregel is currently not documented and therefore not yet supported by the Java driver. As a colleague already mentioned in another [issue](https://github.com/joowani/python-arango/issues/52), you can still use it. In the Java driver you can call every API endpoint with the generic `ArangoDB.execute(Request)` method, i.e.:

```Java
ArangoDB arango = new ArangoDB.Builder().build();

Request request = new Request("_system", RequestType.POST, "/_api/control_pregel");
Map<String, Object> body = new HashMap<>();
body.put("algorithm", "pagerank");
body.put("graphName", "abc");
request.setBody(arango.util().serialize(body));

Response repsonse = arango.execute(request);
```

**Comment by dengwfxx** [comment]
Thanks a lot @mpv1989

**Comment by forest-LF** [comment]
com.arangodb.ArangoDBException: Response: 400, Error: 10 - Edge collection needs to be sharded by shardKeyAttribute parameter ('vertex'), or use SmartGraphs. The current shardKey is: '_key'
请问这个错误怎么解决？

**Comment by forest-LF** [comment]
> @dengwfxx The REST API for pregel is currently not documented and therefore not yet supported by the Java driver. As a colleague already mentioned in another [issue](https://github.com/joowani/python-arango/issues/52), you can still use it. In the Java driver you can call every API endpoint with the generic `ArangoDB.execute(Request)` method, i.e.:
> 
> ```java
> ArangoDB arango = new ArangoDB.Builder().build();
> 
> Request request = new Request("_system", RequestType.POST, "/_api/control_pregel");
> Map<String, Object> body = new HashMap<>();
> body.put("algorithm", "pagerank");
> body.put("graphName", "abc");
> request.setBody(arango.util().serialize(body));
> 
> Response repsonse = arango.execute(request);
> ```

com.arangodb.ArangoDBException: Response: 400, Error: 10 - Edge collection needs to be sharded by shardKeyAttribute parameter ('vertex'), or use SmartGraphs. The current shardKey is: '_key'
May I ask how to solve this error ？

**Comment by rashtao** [comment]
@forest-LF I guess some prerequisites for Pregel are violated in your case: https://www.arangodb.com/docs/3.7/graphs-pregel.html#prerequisites

**Comment by VEADER1005** [comment]
@forest-LF have you solved this my friend?
