### ISSUE TITLE
There are unnecessary failures in src/test/java/com/arangodb/ArangoDBTest if the DB has a pre-existing user other than "root"

### ISSUE THREAD

**Issue by haqer1** [arangodb/arangodb-java-driver#196]
The tests should pass regardless of whether there are such pre-existing users or not.

**Comment by haqer1** [comment]
I had 2 users other than root.
It was failing on
assertThat(users.size(), is(2));
& then on
assertThat(user.getUser(), anyOf(is(ROOT), is(USER)));

PR #197 fixes this.

**Comment by mpv1989** [comment]
@haqer1 Thanks for the fix
