### ISSUE TITLE
Support Kotlin data classes

### ISSUE THREAD

**Issue by slavaatsig** [arangodb/arangodb-java-driver#202]
Because why not?
It started as a StackOverflow [question](https://stackoverflow.com/q/51126054/7598113) and I wonder if amazing geniuses behind ArangoDB could elaborate more about a possibility of such support?

**Comment by mpv1989** [comment]
@slavaatsig Thanks for your input. I will take a look at it. Meanwhile I answered your question with a workaround using Jackson.

**Comment by rashtao** [comment]
@slavaatsig Thanks for reporting!

I created a pull request which you can use as workaround, using the kotlin no-arg maven plugin, here:
https://github.com/slavaatsig/arangodb-jackson-dataformat-velocypack-issue/pull/1/files

Even if the jackson KotlinModule works with data classes (as I verified here: https://github.com/rashtao/arangodb-jackson-dataformat-velocypack-issue/blob/dbg_serde/src/main/kotlin/com/example/issue/main.kt#L16-L21 ), somehow the driver tries accessing the no-arg constructor...

I will investigate further about it.

**Comment by slavaatsig** [comment]
Great thanks @rashtao for the workaround! It worked for me for both cases when my data-class inherits from `DocumentEntity` or if I specify properties `_key`, `_rev`, `_id` explicitly.

_Wait to hear from you regarding your investigation results._

**Comment by rashtao** [comment]
fixed since `java-velocypack 2.2.0`: https://github.com/arangodb/java-velocypack#kotlin-data-classes
