### ISSUE TITLE
Upsert does not seem to work with serialization

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver#207]
I am attempting to do an UPSERT via AQL. The AQL query is:

```
UPSERT @search INSERT @doc REPLACE @doc IN myCollection
```

The code that calls this sets a POJO as the "doc" bind variable, with the `_id`, `_key`, and `_rev` fields equal to null.

Here is the debug log:

```
DEBUG VstCommunicationAsync : Send Message (id=4, head=[1,1,"mydb",2,"\/_api\/cursor",{},{}], body={"bindVars":{"search":{"myId":"LLQD6-89TNKjjgRaVtMc2Q"},"doc":{"_id":null,"_key":null,"_rev":null,"myId":"LLQD6-89TNKjjgRaVtMc2Q", ...},"query":"UPSERT @search INSERT @doc REPLACE @doc IN mycollection"})
```

which results in:

```
Received Message (id=4, head=[1,2,400,{}], body={"error":true,"errorMessage":"AQL: illegal document key (while executing)","code":400,"errorNum":1221})
```

It seems as if the driver is failing to deal with the `_key` value being null?

If I run the same query via the web console, there is no issue at all, even with specifying `_key: null` in the "replace" doc, as expected.

**Comment by mpv1989** [comment]
Hi @rocketraman,

documents with `_key` == `null` are not valid. To solve your problem with the driver you can first serialize your document without `null` values to VelocyPack and then pass it into your bind parameters:

```java
ArangoDB arango = new ArangoDB.Builder().build();
Map<String, Object> bindVars = new HashMap<String, Object>();
bindVars.put("search", search);
bindVars.put("doc",
	arango.util().serialize(doc, new ArangoSerializer.Options().serializeNullValues(false)));

arango.db().query("UPSERT @search INSERT @doc REPLACE @doc IN myCollection", bindVars,
	new AqlQueryOptions(), MyObject.class);
```

**Comment by rocketraman** [comment]
@mpv1989 thanks for your reply. Are you saying there **is** an issue with the driver and serializing it to VPack myself, as you showed, is a workaround? Or are you saying this is the intended behavior? If the latter, then...

> documents with _key == null are not valid.

There do seem to be handlers for this rule in various other parts of the system, which makes sense because clearly for an insert or upsert, `_key` will always be null (or unset).

For example, if I do the same AQL in the web console, and explicitly pass in a bind var with _key = null, the AQL works just fine. Another example is if I do an `insertDocument` call, and explicitly pass in a POJO with _key = null, it also works fine.

It looks like the AQL handler in the java driver just assumes serializeNullValues should be true for all values, whether they are @DocumentField annotated or not. That seems wrong.

**Comment by mpv1989** [comment]
@rocketraman The behavior is expected.

- AQL UPSERT on the server does not allow `_key` == `null`
- Document API on the server also does not allow `_key` == `null`
- The driver does not serialize `null` values when performing `insertDocument`
- The driver does serialize `null` values in `bindVars` when performing a query

The reason for serializing `null` values for `bindVars` is that `null` is a valid value for a bind parameter and `bindVars` in general are not necessarily meant for the use of passing a complete Java POJO as document but calls to the document API like `insertDocument` are meant for this. So no, it is not a bug in the driver and the "workaround" is a valid and recommended way to solve your case.

**Comment by rocketraman** [comment]
@mpv1989 Thank you for the explanation.

**Comment by rocketraman** [comment]
@mpv1989 I'm reopening this because this workaround leads to another issue. If there are other fields in my document that are null, this approach prevents those fields from being sent to the server as well. What I really want here is `serializeNullValues(false)` for the key, id, and rev fields, but `serializeNullValues(true)` for all other fields.

**Comment by rocketraman** [comment]
I've just realized this is the same problem with a regular call to `insertDocument` as well -- null fields are ignored completely, and there doesn't appear to be a way to work around that without doing the insert first, and then a subsequent update with `keepNull=true`.

**Comment by rocketraman** [comment]
Closing this in favor of more general issue #212 .
