### ISSUE TITLE
Long is returned as Double

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver#208]
Issue #4 mentions Long values being returned as a Double value. This was closed because JSON does not have the notion of numeric types, and so all values were returned as Doubles.

I see from https://docs.arangodb.com/3.3/AQL/Fundamentals/DataTypes.html#numeric-literals that all numeric values in ArangoDb are apparently stored as doubles, so normally the explanation provided (less the JSON thing) would seem to remain. However, the VelocyPack specification, which as I understand it, is the underlying data store format of both ArangoDB and of the wire format between the java driver and the database, does support other data types like INT and UINT.

Can someone explain this seeming inconsistency?

**Comment by mpv1989** [comment]
Hi @rocketraman,
Issue #4 is three years old and the statement is not correct anymore. With VelocyPack the driver can differ between `Long` and `Double`.
