### ISSUE TITLE
Document how to do custom serialization with VelocyJack

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver#209]
Document how to do pluggable serialization/deserialization of types with VelocyJack, similar to the way the built-in serializer works.

For example, lets say my source field is a `java.time.Duration` and I want to store that as a vpack Object, how would I go about doing that with VelocyJack?

**Comment by mpv1989** [comment]
Hi @rocketraman,

the class `VelocyJack` provides a method `configure(ConfigureFunction)` over which you can configure the underlying Jackson `ObjectMapper`.

**Comment by rocketraman** [comment]
Ah yes, that's right, thank you.
