### ISSUE TITLE
AQL statement execution with an update returns null

### ISSUE THREAD

**Issue by macadelsol** [arangodb/arangodb-java-driver#210]
Cheers!

I'm performing an update after a doing some stuff in AQL. However the query runs perfectly on the ArangoDb query console and then the cursor return null in the Java Driver.
This happens with any AQL which contains an update, it does not happen if the AQL query does not contain an update statement.
My code:

```
OutputUtils.out("Executing AQL...");
        OutputUtils.out("Query: " + query);
        OutputUtils.out("bind: " + bindVars.get("fch_registro"));
        ArangoCursor<String> cursor = arangoDB.db(configurationMap.get("arango.db_name"))
                .query(query, bindVars,
                        new AqlQueryOptions().batchSize(Integer.parseInt(configurationMap.get("arango.batch_size"))),
                        String.class);
        OutputUtils.out("AQL RESULT..." + cursor.getCount());` //This is always null if thw query contains an update
```

And a test query to replicate the problem:

```
LET comp= (
  FOR comp_ini in COMP
    LIMIT 1
    RETURN comp_ini
)[0]

UPDATE comp WITH { "grafo_score": 1.0 } IN COMP
RETURN {"id_registro": comp.id_registro, "grafo_score": 1.0}
```

Thank you

**Comment by mpv1989** [comment]
Hi @macadelsol,

`cursor.getCount()` is `null` as long as you don't pass `count` == `true` to `AqlQueryOptions`.

```
new AqlQueryOptions().count(true)
```

**Comment by mpv1989** [comment]
I will close this issue. If your problem is still not solved, feel free to open it again.
