### ISSUE TITLE
Cannot insert POJOs and keep fields with nulls using default serializer

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver#212]
This is a follow-up to discussion in issue #207.

It appears that the java driver does not have any way to insert POJO-based documents into ArangoDB using the built-in serializer, while keeping and writing fields with nulls to the db.

The default serializer, when calling `insertDocument(pojo)` appears to serialize the POJO with option `serializeNullValues(false)`. This causes fields in the POJO that are null to be stripped from the document and not inserted into the database with a `null` value, as would be expected.

The underlying reason seems to be that the driver serializes without nulls in order to avoid issues with `_key` being null in an unpersisted POJO. However, that is like using a machine gun to swat a fly: the solution is too broad in its application, and really needs to be addressed without modifying the behavior for fields that user's control.

A workaround appears to be to do a subsequent update after the insert with `keepNull=true` but obviously this is non-optimal.

This also affects bind variables with UPSERT statements as POJOs, which is the subject of #207. The solution discussed by @mpv1989 in that issue suffers from the same problem as described here.

**Comment by rocketraman** [comment]
This workaround (as a Kotlin extension function) removes the _key field after serialization:

```kotlin
/**
  * When doing AQL + bind vars, nulls are normally serialized, but in some cases (e.g. AQL inserts and upserts) we
  * don't want to serialize the ArangoDB _key value. This uses the normal serialization, with nulls, but then
  * post-processes the serialized VPackSlice to remove the _key field, if it exists.
  *
  * See https://github.com/arangodb/arangodb-java-driver/issues/212.
  */
private fun Any.serializeWithoutKey(): VPackSlice {
  return VPackBuilder().apply {
    add(ValueType.OBJECT)
    db.util().serialize(this, ArangoSerializer.Options().serializeNullValues(true))
      .objectIterator()
      .asSequence()
      .filterNot { it.key == "_key" }
      .forEach {
        add(it.key, it.value)
      }
    close()
  }.slice()
}

```

**Comment by mpv1989** [comment]
Hi @rocketraman,

The reason why the driver does not serialize `null` values on default when inserting documents is not that we want to avoid `_key` to be `null`. We believe that it is not the expected behavior when saving POJOs into a schema less NoSQL database that every `null` value has to be persisted. In addition for most operations with AQL it makes no difference if the value is `null` or not existing at all. The same is true when loading and deserializing document back into a POJO.

The only operation where we think serialized `null` values could be necessary is updating documents where some one wants to remove a document field by overriding it with `null`. For this case the driver provides the option `DocumentUpdateOptions.serializeNull(Boolean)` which can be passed to `ArangoCollection.updateDocument(String, T, DocumentUpdateOptions)`.

For every other case you can serialize your POJO to `VPackSlice` with `arango.util().serialize(Object)` and pass that to `insertDocument()` or any other method.

**Comment by rocketraman** [comment]
@mpv1989 I still think the principle of least surprise would be to serialize null fields, and deal with _key specially. Explanation below.

> We believe that it is not the expected behavior when saving POJOs into a schema less NoSQL database that every null value has to be persisted.

I would like to see consistency here: if I have a map with a key->null mapping explicitly contained, I would expect that to be serialized as-is (on the data structure side, a map with a null value is rarely the same thing as that key-value not existing at all, and nulls have to be preserved in order for the map to be deserialized to the same value).

Same with vpack and json, which also recognize a semantic difference between a key with a null value.

> The same is true when loading and deserializing document back into a POJO.

Not at all. For POJOs, the mapping is reversible only if the default value of a field is always null. If the default value of a field in a POJO is non-null, then this approach to serialization / deserialization is not reversible:

```
data class Foo(var _key: String? = null, var bar = "defaultBar")

val f = Foo(bar = null)
arangoDb.insertDocument(f)
val f1 = arangoDb.getDocument(f._key)
println(f1.bar) // prints "defaultBar", oops
```

Furthermore, in languages like Kotlin which have non-nullable types, a value being null is type-safe and significant, and so I would expect the db to reflect that null value as well.

> In addition for most operations with AQL it makes no difference if the value is null or not existing at all. 

Most? If *any* AQL operations do operate differently on null vs non-existent values, then this just bolsters my argument.

**Comment by mpv1989** [comment]
I discussed this with a colleague. Because this is a heavily breaking change and it is unclear for us if this will bring most of the users any real benefit, we decided not to change the actual behavior.

**Comment by rocketraman** [comment]
@mpv1989 If you agree that the current behavior is sub-optimal (and you haven't addressed any of my arguments, so it seems that you do), and the only concern is backward compatibility, then would you accept a pull request that has the "right" behavior wrt nulls, but is opt-in?

I was thinking a new option `ArangoSerializer.Options.roundtripNullValues()`, which defaults to false, but if it is true, then nulls would be sent to the db (except for `_key` of course).

**Comment by rocketraman** [comment]
Hmm, seems like it wouldn't be that easy -- a new serializer is created and configured in most places, with explicit options, so there is no good injection site for this opt-in.
