### ISSUE TITLE
Possible wrong comparsion method inside getEdgeDefinition method

### ISSUE THREAD

**Issue by eugene-kamenev** [arangodb/arangodb-java-driver#22]
Just found that EdgeDefinitionsEntity.getEdgeDefinition(String collectionName) always returns null for me.
I think this is because of == string compare inside getEdgeDefinition method, it should be .equals there.
And also can you please help, how can I update edgeDefinition that already exists.

**Comment by fceller** [comment]
@eugene-kamenev Thanks for spotting this, will fix.

**Comment by fceller** [comment]
@eugene-kamenev I've uploaded a fixed version. Could you test it?

Regarding the edge definition, you should be able to use it similar to the functions described here: https://docs.arangodb.com/General-Graphs/Management.html

Is there a function missing?

**Comment by eugene-kamenev** [comment]
@fceller I am working with GraphEntity, I can create graph structure it is not a problem. But as I see there is no methods in GraphEntity to update/modify scheme, especially edit EdgeDefinitionEntity. From the doc you mentioned above, there is no GraphEntity.editEdgeDefinitions method.

**Comment by fceller** [comment]
@eugene-kamenev will this method work for you?

  /**
   * set the edge definitions (overwrites existing edge definitions)
   * 
   * @param edgeDefinitions the edge definitions to be set
   */
  public void setEdgeDefinitions(List<EdgeDefinitionEntity> edgeDefinitions)

**Comment by eugene-kamenev** [comment]
@fceller No, as I tried, it will not upgrade anything. Just creates.

**Comment by fceller** [comment]
@eugene-kamenev need to check with my colleague.

**Comment by eugene-kamenev** [comment]
@fceller thanks you

BTW I am developing entity mapper in groovylang, similar that i created for orientdb https://github.com/eugene-kamenev/orientdb-groovy and I am experiencing many difficulties, where can I ask questions about arangodb-java-driver and blueprints tinkerpop implementation usage?

**Comment by fceller** [comment]
@eugene-kamenev please feel free to contact

hackers (at) arangodb.org

**Comment by a-brandt** [comment]
Hello @eugene-kamenev 

you have to use the function ```graphReplaceEdgeDefinition``` of the driver.
```
GraphEntity graph = driver.graphReplaceEdgeDefinition("myGraph", "myCollection", newEdgeDefinition);
```
