### ISSUE TITLE
Reached the end of the stream (Connection refused)

### ISSUE THREAD

**Issue by choesang** [arangodb/arangodb-java-driver#221]
```
arangodb version 3.2.15-1
arangodb-java-driver 4.3.4
jdk 8
wildfly 10
```

This error occurs very infrequently and it is hard to pin point the reason. The part of the code gets executed without problem most of the time and misbehaves once  a while. We normally observed that before the error, it is normally creating edges between collections. 

Once this error occurs, most of the queries fail (strangely authentication works).
I have attached our log file. I would be happy if you can throw some hints at the behavior. 

[error.log](https://github.com/arangodb/arangodb-java-driver/files/2318752/error.log)

**Comment by mpv1989** [comment]
Hi @choesang,

The error `Reached the end of the stream` is almost always a sign that the server is not reachable anymore. You should check if you can access the ArangoDB webUI the time your program runs into this error.

If you're running a ArangoDB cluster or single server with failover, you should configure all hosts to be able to use the [fallback feature](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/Drivers/Java/Reference/Setup.md#fallback-hosts) of the driver.

**Comment by mpv1989** [comment]
Hi @choesang,

your code looks good.

> The thing is that authentication always works even when Reached the end of the stream error occurs.

How did you verify that authentication works?

**Comment by choesang** [comment]
> How did you verify that authentication works?

Once i saw the `Connection refused Error` I wanted to make sure which parts of the application is not working, so i tried logging in and out of the application. I could see from the log file that it was hitting the database without problem. Which makes the bug even more intriguing. 

I am still working on reproducing the bug.

**Comment by rvvincelli** [comment]
I am getting this error as well when using `admin-0.4.2.jar` to initialize a `3.6.1` ArangoDB. I can connect via browser to the cluster and login too. I guess this has to be some version mismatch, because the initialization works on `3.5.1`. Thanks,

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
