### ISSUE TITLE
Check hasNext before close ArangoCursor

### ISSUE THREAD

**Issue by joscht-73** [arangodb/arangodb-java-driver#223]
Prevent ArangoDbException "Response: 404, Error: 1600 - cursor not found" if ArangoCursor is already deleted/closed at server.
The try-with-resources Statement throws an ArangoDbException if ArangoCursor has an id and hasNext returns false.
`try (ArangoCursor<BaseDocument> cursor = ...) {
  // some code
}`

**Comment by mpv1989** [comment]
@joscht-73 merged your PR. Thank you again.
