### ISSUE TITLE
How to activate beforeSave or afterUpdate in java driver?

### ISSUE THREAD

**Issue by leenux** [arangodb/arangodb-java-driver#23]
Hi,

I'm searching the method of beforeSave or afterUpdate, but found nothing.
The "before" or "after" same as triger in RDBMS.

Thanks.

**Comment by a-brandt** [comment]
There are no "before" or "after" methods.

I will discuss this issue with my colleagues.

**Comment by mpv1989** [comment]
you can use Foxx for this case. There is no plan to implement that in the driver.
