### ISSUE TITLE
ConnectionSync write timeout setting

### ISSUE THREAD

**Issue by zqhxuyuan** [arangodb/arangodb-java-driver#230]
current ConnectionSync.write() method use future, and get result blocked

```
public Message write(final Message message, final Collection<Chunk> chunks)  {
  return task.get();
}
```

we need timeout setting on task get for long running query/operation, such as:

```
public Message write(final Message message, final Collection<Chunk> chunks)  {
  return task.get(2 * 60, TimeUnit.SECONDS);
}
```

there're already a timeout setting on ConnectionSync.Builder, but that's for connection, not for write.

Do you guys want to support this feature, or can you give reason why not?

**Comment by rashtao** [comment]
You can configure the driver with a `timeout` (either via property file or builder) as documented here:

https://github.com/arangodb/arangodb-java-driver/blob/3ed18bda2ccea36d108ba99052f030e5194c6eaa/docs/Drivers/Java/Reference/Setup.md#driver-setup

This will cause this code to throw `TimeoutException`:
https://github.com/arangodb/arangodb-java-driver/blob/73b2805a9498ec6aac0cab1a6afef74c63fede8b/src/main/java/com/arangodb/internal/velocystream/internal/VstConnectionSync.java#L91
