### ISSUE TITLE
New ConnectionPoolImpl eventually will give ArrayIndexOutOfBounds???

### ISSUE THREAD

**Issue by CarthageKing** [arangodb/arangodb-java-driver#235]
Hi,

I'm looking at https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/internal/net/ConnectionPoolImpl.java connection() method:
```java
	@Override
	public synchronized Connection connection() {
		final Connection connection;
		if (connections.size() < maxConnections) {
			connection = createConnection(host);
			connections.add(connection);
			current++;
		} else {
			final int index = (current++) % connections.size();
			connection = connections.get(index);
		}
		return connection;
	}
```
Is my understanding correct that since `current` is not ever reset to zero, it will eventually overflow into a negative integer. By then, when we call `connections.get(index)` it will give an index out of bounds exception?

Of course this will only happen if the app has been up for a really really really long time, but still...

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/arangodb-java-driver/commit/d7bb22bb6ee7c8ced1ff0b238d4ec8ee1695098d?w=1
