### ISSUE TITLE
Is there non-blocking I/O driver?

### ISSUE THREAD

**Issue by phigoro** [arangodb/arangodb-java-driver#24]
Hello,

Is there a way to use the driver non-blocking I/O way? Maybe through Reactive Streams or direct support of something like RxJava.

**Comment by dothebart** [comment]
For asynchroneous IO in Java we currently only have https://github.com/santo74/vertx-arangodb .

This driver uses a blocking backend. There is no quick way to convert it, which doesn't mean that it couldn't be done. We will discuss this internally next week.
