### ISSUE TITLE
getAccessibleDatabases() works only with access to _system database

### ISSUE THREAD

**Issue by agaengel** [arangodb/arangodb-java-driver#243]
Hi, 

I tried to connect to an authenticated arangodb with the java client and got an not authorised for the getAccessibleDatabases().

if I set the database before with .db("test").getAccessibleDatabases() it works like expected.

Reagards
Alex

**Comment by rashtao** [comment]
This is expected if the user does not have access to `_system` database, but does have access to `test` database.
