### ISSUE TITLE
where can i find source code of version 4.4.2

### ISSUE THREAD

**Issue by Gear-bao** [arangodb/arangodb-java-driver#252]
![屏幕快照 2019-03-19 下午8 46 37](https://user-images.githubusercontent.com/24401252/54606956-1c297f00-4a88-11e9-92db-af86b11fd0d3.png)

i can not find it in `$(git branch a )`

**Comment by Simran-B** [comment]
There are no version branches in this repository, only tags for versions:

![image](https://user-images.githubusercontent.com/7819991/54646107-6289d880-4a9e-11e9-8a99-9454854de05b.png)

According to the changelog, there was never a 4.4.2 version, only 4.4.0, 4.4.1 and 4.5.0:
https://github.com/arangodb/arangodb-java-driver/blob/master/ChangeLog.md#450---2018-06-11

What exactly do you need this version for?

**Comment by Gear-bao** [comment]
Sorry i need the source code  version of 4.2.2

**Comment by Simran-B** [comment]
The 4.2.2 tag points at commit 89aa0ad794154bae6f3d22a0443d006aa74695c1, which is in the master branch. View on GitHub:
https://github.com/arangodb/arangodb-java-driver/tree/4.2.2

4.2.2 release:
https://github.com/arangodb/arangodb-java-driver/releases/tag/4.2.2

Checkout with Git:
```
git clone https://github.com/arangodb/arangodb-java-driver.git
git checkout tags/4.2.2
```
