### ISSUE TITLE
Document not found when inserting a vertex?

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb-java-driver#253]
I get a `com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found` exception, when I call `ArangoVertecCollectionImpl#insertVertex()`.

Isn't that a bug? I'm not sure?

**Comment by MB3r9** [comment]
I get the same exception if i insert a edge with insertEdge if there is a unique constraint violation.

**Comment by rashtao** [comment]
@konsultaner @MB3r9 inserting a vertex and inserting an edge violating a unique constraint is tested here:

https://github.com/arangodb/arangodb-java-driver/blob/583568a363ac9d40336997e0c97aa38ebb100563/src/test/java/com/arangodb/ArangoEdgeCollectionTest.java#L133

and 

https://github.com/arangodb/arangodb-java-driver/blob/ae671ea616c8c447507d1d337a6c990f4be677ab/src/test/java/com/arangodb/ArangoVertexCollectionTest.java#L100

Can you provide the exact steps to reproduce the problem?

**Comment by rashtao** [comment]
Sorry both tests actually fail with ArangoDB 3.4, while they are successful with ArangoDB 3.5

**Comment by tohoku** [comment]
@rashtao If it is working successfully in version 3.5, should we consider https://github.com/arangodb/arangodb/issues/8071 and this issue (#253) fixed?

**Comment by rashtao** [comment]
Since the bugfix has not been backported to all the ArangoDB server supported versions (3.3.x, 3.4.x, 3.5.x), we keep this issue open in order to keep track of the bug, to inform users about this potential misbehaviour and as reminder to test it from the driver once the fix is backported.
