### ISSUE TITLE
Best practice for getting the amount of results of a query

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb-java-driver#255]
Given the case I have an AQL query like this:

```
FOR doc IN Bridge
    FILTER doc.ClientNo == '1004' 
    COLLECT WITH COUNT INTO length
    RETURN length
```

Using Java, what would be the most elegant way of obtaining the result?

I found an article from 2014: https://www.arangodb.com/2014/11/arangodb-java-driver-graphs-2/

Which makes use of:
`CursorEntity<PlainEdgeEntity> result = arangoDriver.executeQuery(query, null, PlainEdgeEntity.class, true, 10);`

But in my case I'm not looking for edges but for Documents, also I'm not sure if this class still exists. Also I'm not using `ArangoDriver` or `ArangoDBConfiguration`, just the `ArangoDB`-Object created by `ArangoDB.Builder()` which doesn't have an `executeQuery`-Method.

I see that a regular cursor has the getCount()-Method which states:

> the total number of result documents available (only available if the query was executed with the count attribute set)

So what should I use if I want to obtain the amount of results from a certain query?

Currently using the arangodb-java-driver Version 5.0.4 on a (For testing purposes offline 3.4.1 ArangoDB)

**Comment by rashtao** [comment]
Closing since outdated, please reopen if still relevant.
