### ISSUE TITLE
Query Cache

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb-java-driver#26]
Please tell me how to implement query cache using Arango Java Driver.

**Comment by jsteemann** [comment]
First of all, you will need a running ArangoDB 2.7 for using the query cache, as the feature was added in that version. Second, you need to turn the query cache either on or set it to demand mode. This can be achieved by setting arangod's configuration option `--database.query-cache-mode` to either `on` or `demand` when starting the server.

After that, identical AQL queries issued by the driver will be served from the cache, at least if the query result is cacheable and no other operation has invalidated the cache in between.

For controlling the server-side query cache from within the driver (e.g. flushing the cache, turning it on or off) there are a few examples in this test case: https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/ArangoDriverQueryCacheTest.java
