### ISSUE TITLE
Removing Debug Logs

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb-java-driver#27]
Can you please tell me how to remove or redirect debug logs of ArangoDB java driver?

**Comment by jsteemann** [comment]
The logging is done via slf4j.
It is normally configured via a file `logback.xml`. 
In that file, there is an element named `root`, which has its `level` attribute set to `info`, `debug` or whatever log level: 
```xml
<root level="info">
```
Setting this to `warn` or `error` will suppress the debug informational log messages.
