### ISSUE TITLE
com.arangodb.ArangoDBException: Response: 412, Error: 1200 - precondition failed

### ISSUE THREAD

**Issue by NingLee** [arangodb/arangodb-java-driver#288]
As mentioned in #165 
I come across 412 error too, but I tested that, when I update non-exist document, It returns 404, not 412.

And when It return 412, the db data is actually updated. 

So I don't know which circumstances can cause 412 error. and Can I ignore this error? because it indeed update success.

**Comment by rashtao** [comment]
@NingLee You should get 404 if the document is not found, 412 if the document is found, but the revision does not match what you expect. You can check the related tests here:

https://github.com/arangodb/arangodb-java-driver/blob/fb856b4777b6ea023c4ed7edfe3fd09ca798a3de/src/test/java/com/arangodb/ArangoCollectionTest.java#L700-L733

So I guess you are updating the document twice (maybe from concurrent threads?) and the second update throws 412.
