### ISSUE TITLE
Function to get raw JSON response

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb-java-driver#29]
Hi,
I added functions to get the raw JSON response with the results from the server:
https://github.com/miguel-porto/arangodb-java-driver

This is handy when the response is composed of JSON docs with different formats and you just want to pass it through without parsing.
Should I make a pull request?
Best,
Miguel

**Comment by a-brandt** [comment]
That is a nice feature. Please make a pull request.

**Comment by miguel-porto** [comment]
Thank you. Then I'll send a signed scan as soon as possible, as it is likely that I'll make more contributions.

**Comment by a-brandt** [comment]
merged
