### ISSUE TITLE
Performance optimization when delivering huge data sets

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb-java-driver#291]
In my projects I use arango to calculate most of the business logic and project data sets. At about 100k of JSON lines of resulting code, I experience low performance of data delivery. Guess this is mostly caused by the serialization process. Which is absolutly ok!

All my servers are optimized to deliver high loads of data by using [zero-copy mechanism of netty](https://netty.io/4.0/api/io/netty/buffer/package-summary.html). Thats why I would like to reduce the cpu usage by skipping the serialization process.

Is it somehow possible to get the very raw velocy stream? I would like to post huge results directly to the client and decode it there. 

It would be perfect if I could somehow get the stream into a direct buffer. Since the driver does not use netty it's probably not possible.

If this issue seems too off topic please just close it.

**Comment by dothebart** [comment]
maybe its a better approach for you to use the document API directly via HTTP in this case? https://www.arangodb.com/docs/stable/http/document-address-and-etag.html

**Comment by konsultaner** [comment]
@dothebart Thanks, this is a good start. 
Is it possible to get a velocypack result instead of a json result? How does this driver connect to arango?

**Comment by dothebart** [comment]
you set the accept-content type `application/x-velocypack` in the HTTP-Headers.

**Comment by konsultaner** [comment]
@dothebart  Thank you! Thats all I needed :)
