### ISSUE TITLE
update httpclient to 4.3.x

### ISSUE THREAD

**Issue by longkerdandy** [arangodb/arangodb-java-driver#3]
Currently arangodb-java-driver uses httpclient 4.2.
httpclient 4.2 and 4.3 have different api structure, which will conflict when put both to a project's dependency.
My project has other library based on httpclient 4.3, and made me difficult to manage the dependency.
So I would suggest update arangodb-java-driver to httpclient 4.3.x, keeps up to date seems a good idea.

**Comment by gschwab** [comment]
Hi!

Sorry, it lastet some time, because of sickness:

I compiled a version with httpclient 4.3.6 and deployed it to the snapshot repository
https://oss.sonatype.org/content/repositories/snapshots/com/arangodb/arangodb-java-driver/2.4-SNAPSHOT/

Hope it meets your needs

**Comment by gschwab** [comment]
We just released a Version 2.4.1 using 4.3.6.
