### ISSUE TITLE
Update docs to point at 6.x.x driver for ArangoDB 3.5.x

### ISSUE THREAD

**Issue by davechallis** [arangodb/arangodb-java-driver#304]
The docs at:

https://github.com/arangodb/arangodb-java-driver/blob/master/docs/Drivers/Java/GettingStarted/README.md

probably need updating to include the 6.x.x drivers for the new ArangoDB 3.5 features (e.g. stream transaction).

**Comment by Simran-B** [comment]
Docs removed from this repo, updated supported versions text in this PR:
https://github.com/arangodb/docs/pull/277
