### ISSUE TITLE
Views API Support

### ISSUE THREAD

**Issue by fdominik** [arangodb/arangodb-java-driver#306]
There is no possibility to Update, Delete view using Java Driver.

**Comment by rashtao** [comment]
If you are asking if those functionalities are implemented, they are here:

- update: https://github.com/arangodb/arangodb-java-driver/blob/fd3ffabd50819b074bf54b5e9649d96db902e1dd/src/main/java/com/arangodb/ArangoSearch.java#L80

- delete: https://github.com/arangodb/arangodb-java-driver/blob/62d64f9299d05842227ae326e3876880261ee46e/src/main/java/com/arangodb/ArangoView.java#L62

**Comment by fdominik** [comment]
Oh you are correct, I havent realized ArangoSearch is the only possiblt type of Views so I didn't pay enough attention to check that this Class has all the update/delete operations I need.
Thank you.
