### ISSUE TITLE
Bug: Method chaining does not work for creating {Hash,Skiplist,...,etc}IndexOptions with named indexes.

### ISSUE THREAD

**Issue by rkhaja** [arangodb/arangodb-java-driver#311]
Attempting to create a HashIndexOptions with method chaining as below does not work.
```
HashIndexOptions hashIndexOptions = new HashIndexOptions()
        .unique(false)
        .sparse(false)
        .deduplicate(false)
        .name("myIndexName");
```
This is also true for SkiplistIndexOptions, and possibly others.

**Comment by rkhaja** [comment]
Hello @rashtao 

I noticed that the [changelog](https://github.com/arangodb/arangodb-java-driver/blob/master/ChangeLog.md) indicates that method chaining for IndexOptions was fixed for version 6.2.0, however, since I am using named indexes I know in fact that method chaining still does not work for IndexOptions using v6.2.0 of the Java driver.

In order to get around this, I changed method chaining into a call sequence, which does work.

```
 HashIndexOptions hashIndexOptions = new HashIndexOptions();
 hashIndexOptions.name(indexName);
 hashIndexOptions.inBackground(inBackground);
 hashIndexOptions.unique(unique);
 hashIndexOptions.sparse(sparse);
 hashIndexOptions.deduplicate(deduplicate);
 ```

I think that while this is a bug, it is not a critical, since the desired end result can be achieved in an alternate manner.  It should however, be fixed at some point, since developers would not expect different results whether using method chaining or a call sequence.

**Comment by rashtao** [comment]
Hi @rkhaja 
the method chaining for index options is actually fixed, as you can see here:

https://github.com/arangodb/arangodb-java-driver/blob/76aa1e1b9fc9d4a0a4f36d77f97d6d4097bbeec0/src/main/java/com/arangodb/model/HashIndexOptions.java

https://github.com/arangodb/arangodb-java-driver/blob/76aa1e1b9fc9d4a0a4f36d77f97d6d4097bbeec0/src/main/java/com/arangodb/model/IndexOptions.java

Eg. I can write now sth. like this:

```java
        HashIndexOptions hashIndexOptions = new HashIndexOptions()
                .name(indexName)
                .inBackground(inBackground)
                .unique(unique)
                .sparse(sparse)
                .deduplicate(deduplicate);
```

**Comment by rkhaja** [comment]
Hello @rashtao,

Sorry I wasn't more clear.  Now it is possible to compile with method chaining, and pass the `hashIndexOptions` into the ensure method, however, when you run it, it throws an exception.

```
arangoCollection.ensureHashIndex(fields, hashIndexOptions);
```

Instead if I pass in the `hashIndexOptions` building it with a call sequence, when the application is run no exception is thrown.

**Comment by rashtao** [comment]
@rkhaja  can you please report here stacktrace, message and type of the exception?

**Comment by rkhaja** [comment]
I've tested again.
I've found that specifically, method chaining **DOES** work for HashIndex and **DOES NOT** work for any of the other indexes. 

The `getThis()` method returns `this` for `HashIndexOptions`.
See: 
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/HashIndexOptions.java#L44

The `getThis()` method returns `null` for `{Fulltext,Geo,Persistent,Skiplist,Ttl}IndexOptions`.
See:
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/FulltextIndexOptions.java#L43
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/GeoIndexOptions.java#L42
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/PersistentIndexOptions.java#L44
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/SkiplistIndexOptions.java#L44
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/TtlIndexOptions.java#L41

When checking the stacktrace, the exception thrown is `java.lang.NullPointerException`, the message is `null`.

**Comment by rashtao** [comment]
Thanks for clarifying, fixed in https://github.com/arangodb/arangodb-java-driver/commit/0ce194d454997b50b68c5e6accae87c46879adbf
