### ISSUE TITLE
typo in ArangoDriver.executeAqlQueryWithDocumentCursorResutl method

### ISSUE THREAD

**Issue by andredasilvapinto** [arangodb/arangodb-java-driver#33]
https://github.com/arangodb/arangodb-java-driver/blob/ccf47e2e4d023e4ddc1fd3618c6a6b4aa4bd0a43/src/main/java/com/arangodb/ArangoDriver.java#L2496

it's also missing javadocs for classDocumentEntity argument

**Comment by a-brandt** [comment]
Fixed in version 2.7.3
