### ISSUE TITLE
ArangoDB Create user + Grant privileges in Kubernetes

### ISSUE THREAD

**Issue by julianbc** [arangodb/arangodb-java-driver#330]
I observed this behaviour operating within a kubernetes cluster (microk8s in this case) of 8 nodes (3 coordinators and 5 dbservers) using the synchronous java driver calls.

It would appear that the calls to ArangoDB.createUser are not synchronous in nature. I have tried different load balancing strategies to ensure I am hitting the same nodes each time. There is a race condition that is created therefore between the createUser call and a subsequent grantAccess call that results in the following error:

Response: 404, Error: 1703 - user not found

By injecting a Thread.sleep of 5 seconds, the call to grantAccess completes successfully. This is problematic as I would think in most use cases where users are granted access it would be immediately following the creation of the user itself. 

Right now we have worked around this. But, the expected behaviour would surely be to not have the server side return on the call until the user is flushed to disk so that a subsequent grant can be performed successfully. 

I can think of many use cases where serialization would need to be guaranteed for operations that take the form of: Create Database, Create Users, Grant Privileges.

**Comment by rashtao** [comment]
It is because such operations are eventual consistent. The coordinator accepting the request will see it immediately while the other coordinators will see the effects with a certain delay. The Kubernetes operator load balancer could route the requests to different coordinators, thus it could be possible to have cases as the one you describe.

**Comment by graetzer** [comment]
Users & permissions are cached at the coordinator level for performance reasons, with kubernetes load balancing you cannot guarantee requests to go to the same instance every time.
Either wait for 2 seconds, or use a JS transaction to execute all user  operations directly on a single coordinator.

**Comment by julianbc** [comment]
OK
