### ISSUE TITLE
Cannot retrieve name from `IndexOptions`

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver#331]
`IndexOptions` has `protected getName()`:

https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/IndexOptions.java#L62

Why is this not public? We have logic that attempts to introspect existing indices and update them if they are out of date, but cannot read the names of the existing indices without using reflection to open up the visibility.

**Comment by rashtao** [comment]
How are you using it exactly?
`IndexOptions` should only be used to write to the db (eg. for creating an index). 
When you read an existing index from the db you get back an `IndexEntity` (https://github.com/arangodb/arangodb-java-driver/blob/d00ddb1afe787199e604424020475953defd46b3/src/main/java/com/arangodb/entity/IndexEntity.java) which has all getters public.

**Comment by rocketraman** [comment]
Thanks for the clarification. Yes, I see reading the indexes from an `ArangoCollection` returns a collection of `IndexEntity`.
