### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by jaredpetersen** [arangodb/arangodb-java-driver#335]
JSON Web Token support has been requested on two separate occasions over the years:
- https://github.com/arangodb/arangodb-java-driver/issues/115
- https://github.com/arangodb/arangodb-java-driver/issues/140

Is this still something under consideration for the backlog? It's a feature that I would really appreciate. While it's not necessary for the VelocyPack setup as described in the first linked issue, it's ideal for the HTTP_JSON protocol.

Other official ArangoDB drivers support JSON Web Token for authentication, why not the Java Driver?
- [JavaScript](https://www.arangodb.com/docs/stable/drivers/js-reference-database.html#databaseusebearerauth)
- [GO](https://godoc.org/github.com/arangodb/go-driver#JWTAuthentication)

**Comment by rashtao** [comment]
Jwt authentication will be supported in the next reactive rewrite of the driver (already implemented here: https://github.com/arangodb/arangodb-java-driver/blob/next/src/main/java/com/arangodb/next/connection/AuthenticationMethod.java#L36). 

You can follow the development in the `next` branch: https://github.com/arangodb/arangodb-java-driver/tree/next
