### ISSUE TITLE
How to retrieve peakMemoryUsage of a query?

### ISSUE THREAD

**Issue by dbenesj** [arangodb/arangodb-java-driver#338]
When using REST API we can see peak memory usage of a query directly available in the response.
But I didn't found any method to retrieve such information in java driver.
Is there such method that I'm missing? If not, could that be added please?

**Comment by rashtao** [comment]
Thanks for spotting it, fixed here: https://github.com/arangodb/arangodb-java-driver/commit/8081c6ea48107a872a8f3f0f0f9b6a2ae474e2fc

**Comment by rashtao** [comment]
released in https://github.com/arangodb/arangodb-java-driver/releases/tag/v6.6.2
