### ISSUE TITLE
[Feature] Allow specifying the return type on Update

### ISSUE THREAD

**Issue by jebbench** [arangodb/arangodb-java-driver#343]
When you pass the return new/old arguments to the `updateDocument(s)` method it will cast the result to the same type as the update argument.

I usually use a map to perform the updates as I don't want to provide all of the entities properties but I would like to receive the updated entity back cast to it's type.

Is it possible to add a third argument to the update methods to specify the expected return type?
It would probably make sense to add the same argument to other methods that return the same type they're given such as insert but these aren't currently an issue for me.

**Comment by rashtao** [comment]
@jebbench I created this PR to address the issue: https://github.com/arangodb/arangodb-java-driver/pull/345
Can you please check if it solves the problem for you?

**Comment by jebbench** [comment]
The updated interfaces look like exactly what I'm after; I've not tried it in practce though - is there an easy way to do so?

**Comment by rashtao** [comment]
You can checkout the related branch and try testing your use cases.
To try it in external projects you can install it to you local maven repository (`mvn install -DskipTests=true -Dgpg.skip`). Before this, to avoid overriding maven artifacts, change the version in the pom, to something like: `<version>6.6.4-SNAPSHOT-PR345</version>`.

**Comment by jebbench** [comment]
@rashtao I can confirm this works for me! Cheers for reacting so quickly and for the patience with my slow responses.

```kotlin
getCollection(client)
    .updateDocuments(
        it,
        DocumentUpdateOptions().keepNull(false).mergeObjects(true).returnNew(true),
        clazz
    )
    .await()
    .documents
    .map { it.new }
```
