### ISSUE TITLE
bugs?Function clearAllMarkedForDeletion without remove the host.

### ISSUE THREAD

**Issue by zz123happy** [arangodb/arangodb-java-driver#346]
Hi there.

I found if some coordinater host did removed from cluster, the 'ExtendedHostResolver' only close the host, but did not remove it from the hostset, the 'clearAllMarkedForDeletion' function in HostSet may have some bugs? I have try to fix it, am I dit in a right way?
 pr：https://github.com/arangodb/arangodb-java-driver/pull/347/files

Thanks very much.

**Comment by rashtao** [comment]
Thanks for reporting and contributing. Your PR should solve the problem.
