### ISSUE TITLE
How to pass user object while creating database

### ISSUE THREAD

**Issue by kesavkolla** [arangodb/arangodb-java-driver#348]
I wanted to create new database using ArangoDB.createDatabase. I was looking to set users who can have access to the newly created database. The DatabaseOptions has no way to set the users. How do I achieve setting users to database?

**Comment by rashtao** [comment]
I have created https://github.com/arangodb/arangodb-java-driver/pull/351 adds `users` options to database creation options. 
Does it solve your problem?

See also API documentation here: https://www.arangodb.com/docs/stable/http/database-database-management.html#create-database
