### ISSUE TITLE
There is no replaceDocumentRaw similar to createDocumentRaw

### ISSUE THREAD

**Issue by gauravkumar37** [arangodb/arangodb-java-driver#35]
There is no `replaceDocumentRaw` similar to `createDocumentRaw`. This is needed when we want to send the raw JSON string when replacing a document.

**Comment by a-brandt** [comment]
I added `updateDocumentRaw()` and `replaceDocumentRaw()`.

[Example](https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/example/document/RawDocumentExample.java)

**Comment by gauravkumar37** [comment]
Thanks @a-brandt for the quick revert.
