### ISSUE TITLE
How to delete all data in a collection

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb-java-driver#355]
How to delete all data in a collection without drop the collection?

The main reason is to keep the index and then overlay all the data

**Comment by rashtao** [comment]
You can use http://arangodb.github.io/arangodb-java-driver/javadoc-6_7/com/arangodb/ArangoCollection.html#truncate--

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
