### ISSUE TITLE
ArangoDBAsync.Builder() not working with SSL

### ISSUE THREAD

**Issue by shreychouhan** [arangodb/arangodb-java-driver#356]
When the application tried to connect with SSL via ArangoAsync get stuck somewhere and don't respond.

Using below properties files and code for connection

arangodb-ssl.properties:
arangodb.hosts=arangodb-demo-enviroemnt.domain.com:443
arangodb.user=root
arangodb.password=root
arangodb.useSsl=true

Code to get connection:
ArangoDBAsync arangoDB = new ArangoDBAsync.Builder()
                    .loadProperties(ArangoDBConfiguration.class.getResourceAsStream("/arangodb-ssl.properties"))
                    .useSsl(true)
                    .build();

When I tried to get Version or any thing from this object "arangoDBAsync", application get stuck somewhere
final ArangoDBVersion version = arangoDBAsync.getVersion().get();

We are using 5.0.1 version of "arangodb-java-driver-async"

The same thing working fine with "ArangoDB.Builder()" but working with "ArangoDBAsync.Builder()".

Is there any issue "ArangoDBAsync"? Can anyone help in this?

**Comment by rashtao** [comment]
You can find here a working example: 
https://github.com/arangodb/arangodb-java-driver/blob/1cbfd30458b050f49fac90297cd6ce536f672a34/src/test/java/com/arangodb/async/ArangoSslTest.java#L58-L76

**Comment by shreychouhan** [comment]
Hi @rashtao 

We are using AWS ALB to access our Arango and its supports https. Arango Instance doesn't have any SSL configuration.

To connect our application with Arango we use ALB as any host and port 443.

**Comment by rashtao** [comment]
Unfortunately the async version of the driver does not support HTTP communication, but VST only.
HTTP communication is only supported by the synchronous driver.

**Comment by shreychouhan** [comment]
Hi @rashtao,

Thanks for the update.

But if we use non-secure connections by keeping only port 80 open, then ArangoDBAsync working fine.

**Comment by rashtao** [comment]
I would expect it not to work either. As far as I know AWS ALB supports only HTTP / HTTPS, while ArangoDBAsync communicates using VST.

**Comment by shreychouhan** [comment]
@rashtao 

Got the solution. Here ALB won't work. If we want to use ArangoDBAsync then have to setup Network Load Balancer in AWS, because that works directly on TCP/TLS instead of HTTP/HTTPS like Application Load Balancer.

Thanks for the help.
