### ISSUE TITLE
Http Protocol Retry Mechanism with Backoff

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb-java-driver#360]
I have been using the Http Protocol as I noticed that the HttpConnection has the apache client with a retry handler.  Currently there's no way to introduce a back off on the retry requests.

Could this be something you guys could introduce as an optional parameter?
Or provide a way to replace the existing retry handler?

Thanks

**Comment by rashtao** [comment]
@aveiros thanks for reporting and pay attention to these considerations when providing your custom retry handler:
https://github.com/arangodb/arangodb-java-driver/pull/362/files#diff-0291bebdb51f8b513337225ba89dedb2R198-R201
