### ISSUE TITLE
Writing 1M documents to arango

### ISSUE THREAD

**Issue by dmalaescu** [arangodb/arangodb-java-driver#364]
Hi, 
I have the following use case where there are 1M documents spreads across a number of threads (e.g 8) and I am trying to efficiently writing those to arango. 
Since there is a quite large number of document I am batch inserting into arango splitting each chunk of documents into smaller chunks of 1000 documents. I am using `insertDocuments` api for interacting with arango. The whole process works but it takes too long, approx 3-4 hours. How the inserting time can be decrease ? Things that I've try so far:
- increase serve.io threads to 8
- increase rocksdb write buffer number to 20
- increase rocksdb write buffer size to 256MB

If I am increasing the chunk size to more than 1000 I've been receiving `Reach of end stream error`

**Comment by rashtao** [comment]
Better performances can be achieved using [bulk-import](https://www.arangodb.com/docs/stable/drivers/java-reference-collection-bulk-import.html).
`Reach of end stream error` exception is thrown when the server closes the connection, you can find the reason of that setting a finer log level for requests on the server side (https://www.arangodb.com/docs/3.7/programs-arangod-log.html).
To further investigate server performances, please ask in the Slack community channels: https://arangodb-community.slack.com/archives/C07NV9NAH or create an issue in https://github.com/arangodb/arangodb

**Comment by dmalaescu** [comment]
Seems that bulk-import does improve a lot the writing time. Thanks for helping!

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
