### ISSUE TITLE
Did not add clazz to model when deserialize entity

### ISSUE THREAD

**Issue by menesty** [arangodb/arangodb-java-driver#366]
After serialization object no marker field for class as I understand from the documentation it should enable by default, I have tried manually enable it but no result.
Driver version 6.7.5
```java
new ArangoDB.Builder()
            .registerSerializer(LocalDateTime.class, (builder, attribute, value, context) -> builder.add(attribute, JavaTimeUtil.format(value)))
            .registerSerializer(LocalDate.class, (builder, attribute, value, context) -> builder.add(attribute, JavaTimeUtil.format(value)))

            .registerDeserializer(LocalDateTime.class, (parent, vpack, context) -> (vpack.isString()) ? JavaTimeUtil.parseLocalDateTime(vpack.getAsString())
                    : vpack.getAsDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime())
            .registerDeserializer(LocalDate.class, (parent, vpack, context) -> (vpack.isString()) ? JavaTimeUtil.parseLocalDate(vpack.getAsString())
                    : vpack.getAsDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate())
            .registerModule(new VPackModule() {
              @Override
              public <C extends VPackSetupContext<C>> void setup(final C context) {
                context.useTypeHints(true);
              }
            })
            .host(configuration.getUrl(), 8529)
            .user(configuration.getUsername())
            .password(configuration.getPassword()).build().db(configuration.getDatabase());
```

**Comment by rashtao** [comment]
Type hint is only added if the referencing element type is not equal to the class of the value being serialized. This allows and is needed for polymorphic deserialization.

In case you need further customisations, you can either write and register a custom serializer for your classes or use the [jackson-dataformat-velocypack](https://github.com/arangodb/jackson-dataformat-velocypack#within-arangodb-java-driver) serialization, which allows you using standard jackson databind API, thus controlling type hints in a more flexible way.

**Comment by menesty** [comment]
Of course, it is a kind of workaround  maybe it not clearly explain in the documentation https://www.arangodb.com/docs/3.7/drivers/java-reference-serialization.html
"The Java VelocyPack library automatically adds a type hint field (named _class by default) "
Maybe need to change it - because in my case I return mix document from the different collection in one result - so in my case, I prefer to have this _class field in all documents :)

> Type hint is only added if the referencing element type is not equal to the class of the value being serialized. This allows and is needed for polymorphic deserialization.
> 
> In case you need further customisations, you can either write and register a custom serializer for your classes or use the [jackson-dataformat-velocypack](https://github.com/arangodb/jackson-dataformat-velocypack#within-arangodb-java-driver) serialization, which allows you using standard jackson databind API, thus controlling type hints in a more flexible way.

**Comment by menesty** [comment]
Have use jackson-dataformat-velocypack as you recommend - I think need to change the description in the documentation.
