### ISSUE TITLE
How Do I Set the Read Timeout for Querying Data?

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb-java-driver#367]
I didn't find the relevant description in the document.

By the way, Is there any reference document for improving the AQL statement performance?

That's what I'm using at present：
AqlQueryOptions options = new AqlQueryOptions().cache(true);
ArangoCursor<T> cursor = arango.query(aql, bindVars, options, type);

thanks for help.

**Comment by rashtao** [comment]
You can use the `maxRuntime` attribute, see http://arangodb.github.io/arangodb-java-driver/javadoc-6_7/com/arangodb/model/AqlQueryOptions.html#maxRuntime-java.lang.Double-

About AQL performances, here is the related documentation to investigate further:
https://www.arangodb.com/docs/stable/aql/execution-and-performance.html

From the Java driver you can control optimizer rules setting the `rules` attribute, see http://arangodb.github.io/arangodb-java-driver/javadoc-6_7/com/arangodb/model/AqlQueryOptions.html#rules-java.util.Collection-

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
