### ISSUE TITLE
Classic begin -> commit/rollback transactions

### ISSUE THREAD

**Issue by pienikrz** [arangodb/arangodb-java-driver#40]
Hi,

Do you have plans to add support for classic begin -> commit/rollback transactions in additional to current  db._executeTransaction(object) ?

**Comment by dothebart** [comment]
Hi, 
in the current state of the server you can have transactions in server side javascript:
So you state `db._executeTransaction()` and then you execute queries like: `db._query('FOR u IN ...')` If a query or your javascript code throws an exception, the transaction is rolled back.

So If you want transaction spanning several queries the best way to achieve this is to write a foxx service, and call that from java.
