### ISSUE TITLE
WAL Support

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb-java-driver#402]
I was looking through the docs and there doesn't seem to be any support for the write-ahead log in the Java driver? I'm in the process of migrating my Scarango project (Scala Driver) to being built on top of the Java driver, but I use the WAL for reactive listeners on the database. Is there any way to accomplish this in the Java driver, or do I need to write this functionality from scratch?

**Comment by dothebart** [comment]
Hi, 
the WAL driver API is documented, but marked as internal. Hence its not part of regular drivers. Even more so, its implementation may (and soon will) change.

**Comment by darkfrog26** [comment]
How soon are we talking? Can I get a link to the docs?

**Comment by rashtao** [comment]
Closing since at this stage the topic is unrelated to the Java driver.
Feel free to ask and discuss it the community Slack or ArangoDB github repository.

**Comment by darkfrog26** [comment]
@rashtao any updates on this?

**Comment by rashtao** [comment]
Cluster-wide CDC (as public API) should be part of ArangoDB 4.x, although it is unclear a timeline for the release.

**Comment by darkfrog26** [comment]
@rashtao thanks for the response. Is there a ticket I can follow to monitor the progress?

**Comment by rashtao** [comment]
https://github.com/arangodb/arangodb/issues/602 seems to me the most relevant ticket about this topic.
