### ISSUE TITLE
Cache Issues

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb-java-driver#41]
I was trying to implement the query cache for large queries.
When i check if the document cursor is cached or not, it shows true. But i see no performance improvements in the query time processing.
However using the same query from arangodb web interface shows high performance improvements.

**Comment by mpv1989** [comment]
Hi,
i answered you on stackoverflow:
http://stackoverflow.com/questions/37627134/arangodb-java-driver-caching-not-working

**Comment by mpv1989** [comment]
Issue clarified via stackoverflow, close
