### ISSUE TITLE
driver.importDocuments API improvements

### ISSUE THREAD

**Issue by gauravkumar37** [arangodb/arangodb-java-driver#42]
Current implementation of `driver.importDocuments` does not provide any means to customize it.
The following provisions should be present in the API:

- [x] Provide the value of the flag `onDuplicate`. In fact, to make it more genetic, we should have a `Map` of query parameters in the API that can have any number of parameters.
- [x] Provide a method that takes raw JSON similar to the likes of `updateDocumentRaw`
- [ ] ArangoDB's `/import` API provides a flag `details` which when used provides more info on the records that failed for any reason. Provide a way to fetch the `details` object in the response along with the already present counts of documents.

**Comment by mpv1989** [comment]
We improved the importDocuments methods in Version 3.0.0.
see (https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/InternalImportDriver.java).

The flag `details` will be add in Version 3.0.1.

**Comment by gauravkumar37** [comment]
I gave latest version a try and am happy with the new API, thanks.
Waiting for v3.0.1 for `details` flag :+1:

**Comment by mpv1989** [comment]
We released Version 3.0.1 today. Have fun with the `details` flag :-)

**Comment by gauravkumar37** [comment]
@mpv1989 I played around with the `details` flag today.
I have a unique index on `pk_id` field. I tried to insert 2 documents with different `_key` and the same `pk_id`. The `importResultEntity` gave me 1 created, 1 error document as expected. But details gave me an empty list. In what cases the `details` flag is populated?

**Comment by mpv1989** [comment]
I added a test for your usecase, where getting the expected result. ([https://github.com/arangodb/arangodb-java-driver/blob/3.0/src/test/java/com/arangodb/ArangoDriverImportTest.java](url) Method: test_import_index_with_errors_details() at Line 349).

To get filled `details`, you have to set the `details` flag in the ImportOptions to `true`.
Possible reasons for filled `details`, except your usecase, are for example: invalide JSON, missing _from/_to in edge-documents.

**Comment by gauravkumar37** [comment]
Yup, got it working, thanks a ton.
