### ISSUE TITLE
Socket InputStream read data as Integer and Long even when data is header start line

### ISSUE THREAD

**Issue by leeby-devel** [arangodb/arangodb-java-driver#428]
**ArangoDB Version: 3.7.13**
**Driver Version: 6.16.0**

I've turned on debug mode for our spring application debugging.

But after debug mode is turned on, NPE that didn't happen before occasionally occurred.

The point is on line 332

https://github.com/arangodb/arangodb-java-driver/blob/17cb79ac0f08094b741e440125c30b1053be3aac/src/main/java/com/arangodb/internal/velocystream/internal/VstConnection.java#L314-L336

It's because `chunk.getMessageId()` has wrong Long value as hash key
So `sendTimestamps.get(chunk.getMessageId())` is to be null

<img width="1414" alt="2022-02-17 7 18 22" src="https://user-images.githubusercontent.com/98696463/154481347-3dde092e-4a77-4bd0-a5a8-91bf979cca0a.png">

As a result of reading header start line in buffer as Long type not as String type,
`7233135182548579360L` was assigned to the `messageId`.

Contents of buffer is as follow
<img width="948" alt="스크린샷 2022-02-17 오후 8 21 55" src="https://user-images.githubusercontent.com/98696463/154482944-5be817bb-807e-468d-82f1-57e2bc2e491a.png">

<img width="663" alt="스크린샷 2022-02-17 오후 7 20 03" src="https://user-images.githubusercontent.com/98696463/154482981-38241f14-f109-4bc3-9874-97e6cdd9b21a.png">

I think this code needs to be exception handled

Thanks

**Comment by rashtao** [comment]
The response received is not compliant with VST spec and the DB should never reply this way. Can you provide a code snippet to reproduce the problem?

**Comment by rashtao** [comment]
Closing for now, please reopen in case of further updates.
