### ISSUE TITLE
ArangoDriver.getAqlFunctions(String) does not uses the defaultDatabase setting

### ISSUE THREAD

**Issue by rwe17** [arangodb/arangodb-java-driver#43]
There is a slight bug in the method ArangoDriver.getAqlFunctions() which causes that only the functions in the system database will be retrieved. 

getAqlFunctions() delegates to method InternalAqlFunctionsDriverImpl.getAqlFunctions(String) which builds the request to retrieve the functions. And here is the bug:

  HttpResponseEntity res = httpManager.doGet(createEndpointUrl(null, API_AQLFUNCTION + appendix));

In order to use the propper database this should be:
  HttpResponseEntity res = httpManager.doGet(createEndpointUrl(configure.getDefaultDatabase(), API_AQLFUNCTION + appendix));

Thanks
Ralf

**Comment by mpv1989** [comment]
Thanks. Fixed in Version 3.0.1 (released today)

**Comment by antonsarov** [comment]
Sorry for poking around on a closed issue but can we merge (some) of the changes from https://github.com/arangodb/arangodb-java-driver/commit/e76fc0610f93fb27331004a51d0147bc730901b3 also to the 2.7 branch? We are using 2.7.4 for now and just ran into this bug.

Best regards
Anton

**Comment by mpv1989** [comment]
Hi Anton,

no problem. I released version 2.7.5 today with several bugfixes (including this one).

Best regards
Mark

**Comment by antonsarov** [comment]
Thank you, Mark!
