### ISSUE TITLE
Timeout waiting to lock key Operation timed out: Timeout waiting to lock key

### ISSUE THREAD

**Issue by B0BAI** [arangodb/arangodb-java-driver#430]
We tend to get this issue intermittently when performing an **update** operation on this particular document when we have  a high load.

**Comment by rashtao** [comment]
This error is generated from the db side due to the high level of concurrent requests trying writing the same document.

**Comment by B0BAI** [comment]
What's a sensible solution? Synchronising?

**Comment by rashtao** [comment]
Please refer to the related discussion about the topic in ArangoDB repository: https://github.com/arangodb/arangodb/issues/9702
