### ISSUE TITLE
singleOf  don't work with KoinScopeComponent

### ISSUE THREAD

**Issue by aviadmini** [arangodb/arangodb-java-driver#432]
Using `singleOf` overloads for a class that implements `KoinScopeComponent` doesn't work (`Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'org.koin.core.scope.Scope'. Check your definitions!`)
v3.2.0-beta-1 here

Had to revert back to using `single` that supplies scope in receiver lambda

**Comment by rashtao** [comment]
How is this problem related to the ArangoDB Java driver? Can you please provide additional context and code snippet to reproduce the problem?

**Comment by aviadmini** [comment]
Ouch. This is definitely the wrong repository. Closing 🤦
