### ISSUE TITLE
Upsert Document

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb-java-driver#45]
Team,

  Is there any way to do an upsert using the java driver.

Thanks & Regards,
Sajeev Ramakrishnan

**Comment by mpv1989** [comment]
Hi,
you can perform an upsert only via AQL.
[https://docs.arangodb.com/3.0/AQL/Operations/Upsert.html](https://docs.arangodb.com/3.0/AQL/Operations/Upsert.html)

Regards,
Mark

**Comment by sajeevpr** [comment]
Hi Mark,
  Thanks for your response. So can I use updateDocument for update and insert using the java API.

Regards,
Sajeev

**Comment by mpv1989** [comment]
With `updateDocument` you can only update a document, if it doesn't exists you get an error.
With `createDocument` you can only insert a document, if it exists already you get an error.
With `executeAqlQuery` you can perform an AQL to upsert a document.

If you never worked with AQL before, check out our documentation: [https://docs.arangodb.com/3.0/AQL/index.html](https://docs.arangodb.com/3.0/AQL/index.html)

**Comment by rocketraman** [comment]
> With executeAqlQuery you can perform an AQL to upsert a document.

For future searchers, this is called `query` now. See https://github.com/arangodb/arangodb-java-driver/blob/master/docs/Drivers/Java/Reference/Database/Queries.md.

**Comment by udarajag** [comment]
Is the upsert function available using java driver yet?

**Comment by rashtao** [comment]
In addition you can also `insertDocument` setting `overwrite` in the provided `DocumentCreateOptions`, which means:

```java
	 * @param overwrite If set to true, the insert becomes a replace-insert. If a document with the same {@code _key}
	 *                  already exists the new document is not rejected with unique constraint violated but will replace
	 *                  the old document.
```

https://github.com/arangodb/arangodb-java-driver/blob/bcf2f88a3d73db01038c958e086be40117dcb45a/src/main/java/com/arangodb/model/DocumentCreateOptions.java#L87-L97
