### ISSUE TITLE
how to connect arangodb with domain name? rather than  host:port

### ISSUE THREAD

**Issue by lunbin** [arangodb/arangodb-java-driver#452]
we have an arangodb server, expose domain to provide service, i do not know the host and the port.  how can i connect it.  is it necessary to use this form of host:port?

**Comment by rashtao** [comment]
How is the domain name resolved? Do you get the port in the resolution? I.e. does it resolve to SRV records?

As of now the driver requires hostname and port for every host entry, therefore in the case above you must resolve the domain name manually and then configure the driver providing the resolved host:port values.

**Comment by lunbin** [comment]
our arangodb deployed on k8s,  and create a ingress map to service(cluster ip). and now ,  i ask the operator staff to create nodeport service for me.

**Comment by ajanikow** [comment]
Hello!

`host:port` can also be `domain:port` - just domain parts must be able to resolve to IP.

**Comment by lunbin** [comment]
thank you.  i have fixed it. this question can be closed.
