### ISSUE TITLE
Connection forces to specify host and port always

### ISSUE THREAD

**Issue by JuanEL0** [arangodb/arangodb-java-driver#453]
Hi everyone, I don't know if this is just a specific case, but here it is:

In my company we have an instance of Arango exposed through a subdomain name but I can't connect to it this way because the default connection options force us to always specify host and port and not just host.

Of course I got the host and port options information and everything is fine, but I can imagine some cases where the developer can't have access to this information.

**Comment by rashtao** [comment]
How is the subdomain name resolved? Do you get the port in the resolution? I.e. does it resolve to SRV records?

As of now the driver requires hostname and port for every host entry, therefore in the case above you must resolve the subdomain name manually and then configure the driver providing the resolved host:port values.

**Comment by rashtao** [comment]
Closing for now, please reopen in case of further questions.
