### ISSUE TITLE
[3.10] Computed Values Support

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb-java-driver#459]
My Scala driver depends on the Java Driver now (https://github.com/outr/scarango) and I'm hoping to start adding support for the new Computed Values (https://www.arangodb.com/docs/3.10/release-notes-new-features310.html#computed-values) feature in 3.10 soon. I was wondering when that is likely to be added?

**Comment by rashtao** [comment]
Support to computed values has been added in https://github.com/arangodb/arangodb-java-driver/commit/b86f1c56ae437e7379110cffbab8c3a19b6dd5a7, but not released yet.

**Comment by darkfrog26** [comment]
@rashtao awesome, thank you!
