### ISSUE TITLE
Expose setting 'options' in AQL Query Options

### ISSUE THREAD

**Issue by gauravkumar37** [arangodb/arangodb-java-driver#47]
As mentioned `https://docs.arangodb.com/2.8/HttpAqlQueryCursor/AccessingCursors.html`, there is an `options` flag which lets us control `profile` for additional query profiling. Turns out it is enabled by default and I would like to turn it off.
Currently, there is no option to control this from AQL Query Options.
It should also be possible to fetch the `extra.stats` parameter returned in the cursor output. It is only possible to access this when using `driver.executeAqlQuery` via `cursorResult.getEntity.getExtra`. However, it is not available via `driver.executeDocumentQuery`.
Which one out of the both should be used and when?

**Comment by mpv1989** [comment]
Thanks,
we will add the flags and the extra-attribute in the next version.

> Which one out of the both should be used and when?

`driver.executeDocumentQuery` returns a cursor of `DocumentEntity`. In this wrapper class you have fields for `_id`, `_key` and `_rev`. You only need `DocumentEntity`, when you need one of these fields, and your own entity-class does not contains them.

**Comment by a-brandt** [comment]
Fixed in version 3.0.2.
