### ISSUE TITLE
Support persistent index creation

### ISSUE THREAD

**Issue by gyscos** [arangodb/arangodb-java-driver#48]
ArangoDB 3.0 apparently adds a new "persistent" index type.
This currently is not part of the provided Index Types in this driver.

**Comment by a-brandt** [comment]
Fixed in version 3.0.2.

**Comment by gyscos** [comment]
I see - but why no `createPersistentIndex` in `ArangoDriver`?

**Comment by a-brandt** [comment]
You can create the index by ```driver.createIndex(collectionName, IndexType.PERSISTENT, ...)```.
