### ISSUE TITLE
Why does you not throw ArangoDBException in HttpCommunication.java, the inserting action was failed but I cannot handle this event

### ISSUE THREAD

**Issue by truongmaicongtri** [arangodb/arangodb-java-driver#485]
`catch (final IOException e) {`
`                   hostHandler.fail(e);`
`                    if (hostHandle != null && hostHandle.getHost() != null) {`
`                        hostHandle.setHost(null);`
`                    }`
`                    final Host failedHost = host;`
`                    host = hostHandler.get(hostHandle, accessType);`
`                    if (host != null) {`
`                        LOGGER.warn(String.format("Could not connect to %s", failedHost.getDescription()), e);`
`                        LOGGER.warn(String.format("Could not connect to %s. Try connecting to %s",`
`                                failedHost.getDescription(), host.getDescription()));`
`                        <why does you not throw ArangoDBException? at here>`
`                    } else {`
`                        LOGGER.error(e.getMessage(), e);`
`                        throw new ArangoDBException(e);`
`                    }`
`                }`

**Comment by rashtao** [comment]
The exception is not thrown there because there is another host to try. The exception will be thrown when the host returned from the host handler is null: https://github.com/arangodb/arangodb-java-driver/blob/4626f1067931b89f266abbee12348f254dc8065d/src/main/java/com/arangodb/internal/http/HttpCommunication.java#L83-L113

**Comment by rashtao** [comment]
Closing as invalid, please reopen in case the problem persists.
