### ISSUE TITLE
Thread safe collection entries?

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb-java-driver#49]
I use the arango driver in a multithreaded environment and wanted to know if the CollectionEntry class is thread safe or not. I would like to instantiate it once as a public static final field.

**Comment by mpv1989** [comment]
do you mean [CollectionEntity](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/entity/CollectionEntity.java)? Then the answer is, yes.

**Comment by konsultaner** [comment]
Yes, I do! Thanks
