### ISSUE TITLE
graph.setEdgeDefinitions(edgeDefinitions) does not persist

### ISSUE THREAD

**Issue by normunds** [arangodb/arangodb-java-driver#5]
Once the graph is created it is not possible to change the edge collections. graph.setEdgeDefinitions(edgeDefinitions) has not effect (version 2.5.0)

**Comment by gschwab** [comment]
There is no persistence on the entity themselves. To persist an entity, you have to use the driver.
Creating a GraphEntity with
     GraphEntity graph = new GraphEntity();
and modifying this instance with e.g.
     graph.setEdgeDefinitions(edgeDefinitions);
will not persist anything, not the graph and not the added edge definitions.

I added a new method (2.4.4 and 2.5.1)
     GraphEntity driver.createGraph(GraphEntity);
So you can create a GraphEntity object and and modify it as you want. After that, you can create the persist the graph.

Atm there is no method to update a complete graph object, so if you want to modify an existing graph (peristet) you have to use the driver methods like
     driver.graphCreateEdgeDefinition() etc.

**Comment by normunds** [comment]
So what in your opinion is the use case for 
`GraphEntity graph = new GraphEntity();`
`graph.setEdgeDefinitions(edgeDefinitions);`
and other setters? Why you provide a method to create an empty graph, then allow modify it, if we cannot persist the modified object (and cannot use as modified, because it is at odds with the saved version)? Maybe it's possible 
And `driver.graphCreateEdgeDefinition()` at best allows to add a new edge collection, not to replace one edge collection with another.
It seems there is a REST api the allows to replace the edge collection:
*Replace an edge definition*
`POST /_api/gharial/graph-name/edge/definition-name`
