### ISSUE TITLE
InternalSerdeImpl does not serialize bindVars correctly

### ISSUE THREAD

**Issue by idoub** [arangodb/arangodb-java-driver#500]
It appears that the new serialization doesn't work correctly for bindVars on a query.

When I turn on FINE logging I see the following lines

```
FINE: Send Request [id=101]: {requestType=POST, database='MyDatabase', url='/_api/cursor', parameters={}, headers={x-arango-driver=JavaDriver/7.0.0 (JVM/17), content-type=application/x-velocypack, accept=application/x-velocypack}} {"count":true,"cache":false,"bindVars":{"alias":7545298,"@collection":7240910},"query":"FOR d IN @@collection FILTER d.alias == @alias LIMIT 50000 RETURN d","options":{"optimizer":{},"fullCount":true},"fullCount":true}
```

as well as

```
FINE: Received Response [id=101]: {statusCode=400, headers={x-arango-queue-time-seconds=0.000000}} {"code":400,"error":true,"errorMessage":"bind parameter '@collection' has an invalid value or type","errorNum":1553}
```

and when I step through the code and put a breakpoint in `InternalSerdeImpl.serialize:52` I can run `mapper.readValue(mapper.writeValueAsBytes(value), Object.class)` and see that it does indeed convert my string values to those integers 7545298 and 7240910.

I have tried it with both the default `com.arangodb:http-protocol` and `com.arangodb:jackson-serde-json` libraries as well as with the `com.arangodb:vst-protocol` and `com.arangodb:jackson-serde-vpack` libraries. Other than updating the `driver.query` [parameter ordering](https://github.com/arangodb/docs/blob/main/drivers/java-changes-v7.md#api-methods-changes), code is the same as it was using v6.21.0 of the library.

**Comment by rashtao** [comment]
Can you please provide a code snippet to reproduce the issue?

BindVars serialization is tested here:

https://github.com/arangodb/arangodb-java-driver/blob/898b9d88a51291402d3592ab4e6f6eb471b7bc56/driver/src/test/java/com/arangodb/ArangoDatabaseTest.java#L882-L902

Note that bindVars values should normally be serialized by the user serde, i.e. by default by `JacksonSerdeImpl.serialize()`.

**Comment by rashtao** [comment]
Closing as invalid, please reopen in case the problem persists.
