### ISSUE TITLE
Cursor(Raw)Result: shouldn't they implement the Iterator interface instead of the Iterable interface?

### ISSUE THREAD

**Issue by christian-lechner** [arangodb/arangodb-java-driver#51]
Hello!

I'm currently working with [`CursorResult`](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/CursorResult.java) and [`CursorRawResult`](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/CursorRawResult.java) classes. Both of them implement the `Iterable` interface, enabling us to iterate **more than once** over the result.

However, the `iterator` method returns always the same iterator and thus the result can only be consumed once.
```java
@Override
public Iterator<T> iterator() {
		if (iter == null) {
			iter = new CursorIterator();
		}
		return iter;
	}
```
It makes perfectly sense that the result can only be consumed once, because the cursor of the DB is also moved with `continueQuery` method. One could aggregate the results instead of overwriting it and always provide a new iterator. But the list can grow huge and there is also the `asList` method.

Wouldn't it be more clear for the user if `CursorResult` and `CursorRawResult` would implement the `Iterator` interface, indicating that it can only be consumed once? 

And the `asList` method returns only a complete list if no object is already consumed from the iterator. Should the `asList` method be called `asListRemaining` just like the `forEachRemaining` of the `Iterator` interface? Or completely remove this method to avoid confusing?

**Comment by mpv1989** [comment]
Thanks for your feedback. This is a really good point.

Currently we rewrite the Java Driver. It gets a new api, async and VelocyPack/VelocyStream under the hood.
I already changed the implementation of our new cursor with your input. (which your can find [here](https://github.com/arangodb/arangodb-java-driver/blob/4.0/src/main/java/com/arangodb/ArangoCursor.java))

The new driver version will probably be released by the end of the month, but you can already try it out. ([Branch 4.0](https://github.com/arangodb/arangodb-java-driver/tree/4.0))
Your feedback is much appreciated.

**Comment by christian-lechner** [comment]
Awesome! New driver looks great, looking forward to it. I will swtich to the new version in my new project.

4.0 driver version needs ArangoDB 3.1. Can you tell me when ArangoDB 3.1 will be released?

**Comment by mpv1989** [comment]
We will release the first beta by the beginning of october, at this time we will release the driver in version 4.0.0 too.

**Comment by christian-lechner** [comment]
Thank you!
