### ISSUE TITLE
Interfering Jackson annotations

### ISSUE THREAD

**Issue by nishisan** [arangodb/arangodb-java-driver#512]
Hello, we recently upgraded the drivers from version 6 to version 7. After the upgrade, the replacements for @DocumentField(DocumentField.Type.KEY) and @DocumentField(DocumentField.Type.ID) introduced new annotations: @InternalKey and @InternalId.

The problem we encountered is that these new annotations come with a @JsonProperty, which replaces the original property name of the class, thereby breaking existing integrations prior to version 7. The workaround we found was to add an extra @JsonProperty annotation to the property fields in each class.

**Comment by rashtao** [comment]
Thanks for reporting it. It will be addressed by #513 , when complete.
In the meantime you can work around it using different classes to carry data across different layers of your application, or by customizing the driver user-serde as in #513.

**Comment by nishisan** [comment]
That is a too expensive workarround, in mean time we rolled back to version 6. As we figured out that json serialization with spring api´s and arangodb´s java driver will break the existing api contracts.
Thansk for the feedback.
