### ISSUE TITLE
Arango query is flattening  nested attributes

### ISSUE THREAD

**Issue by Gajanana** [arangodb/arangodb-java-driver#514]
I have document as below

```
{
"att1": 32,
"att2": 36,
"properties" :{
"att3" : "str1",
"att4": "str2"
}
```
I am passing type as _BaseDocument.class_ in arango query
```
<T> ArangoCursor<T> query(String query, Class<T> type, Map<String, Object> bindVars, AqlQueryOptions options);
```     
Earlier  in 6.x . retrieving  _att3_ was done as below

```
(String) ((HashMap<String, Object>)baseDocument.getAttribute("properties")).get("att3"))
```
Now in 7.X basedocument is flattened in returned basedocument and I have to retrieve _att3_ as below whereas i was expecting it to work as before matching my arango document structure
```
(String) (baseDocument.getAttribute("att3"))
```

**Comment by rashtao** [comment]
This is a change introduced since version 7. 
To get all properties as `Map<String, Object>` you can still use `BaseDocument#getProperties()`.

**Comment by Gajanana** [comment]
What will happen if we have same attribute as nested as well as in outer layer Ex 
```
{
"did": 32,
"att0": 36,
"properties" :{
"did" : "str1",
"att1": "str2"
}
```

**Comment by rashtao** [comment]
Thanks for clarifying, the PR above should fix it.
