### ISSUE TITLE
[ERROR] Failed to execute goal on project Save: Could not resolve dependencies f or project com.huawei.arangodb.Save:Save:jar:1.0-SNAPSHOT: Failure to find com.a rangodb:arangodb-java-driver:jar:3.0.3 in http://10.175.102.184:8081/nexus/conte nt/groups/public/ was cached in the local repository, resolution will not be rea ttempted until the update interval of big has elapsed or updates are forced -> [ Help 1]  

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb-java-driver#53]
When I add the following code to my pom.xml(the version of my arangodb is 3.0.5):

 <groupId>com.arangodb</groupId>
<artifactId>arangodb-java-driver</artifactId>
 <version>3.0.3</version>

 and  I  use " mvn install" to get the dependency, it throws a error:

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Save: Could not resolve dependencies f
or project com.huawei.arangodb.Save:Save:jar:1.0-SNAPSHOT: Failure to find com.a
rangodb:arangodb-java-driver:jar:3.0.3 in http://10.175.102.184:8081/nexus/conte
nt/groups/public/ was cached in the local repository, resolution will not be rea
ttempted until the update interval of big has elapsed or updates are forced -> [
Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

When I put arangodb-java-driver-3.0.3.jar into my local Maven libs, it still has this problem.

Any help is highly apprechiated.

**Comment by mpv1989** [comment]
We deploy our java-driver in the central maven repository, there is no need of additional repository location. (see [here](http://search.maven.org/#artifactdetails%7Ccom.arangodb%7Carangodb-java-driver%7C3.0.3%7Cjar))

**Comment by saliormoon** [comment]
Well, if so ,why did  it throw the error above? Would you like to help me with this problem? @mpv1989

**Comment by mpv1989** [comment]
Can you post the content of your pom.xml?

**Comment by saliormoon** [comment]
Ok. look at this:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.huawei.arangodb.Save</groupId>
    <artifactId>Save</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.arangodb</groupId>
            <artifactId>arangodb-java-driver</artifactId>
            <version>3.0.3</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.10</version>
        </dependency>

    </dependencies>

</project>

**Comment by saliormoon** [comment]
It still has the problem  now. Any suggestion is highly appreciated.

**Comment by mpv1989** [comment]
The pom looks ok. There has to be an other source which produces the problem. Do you have a setting.xml or anything else that can influence your project?

**Comment by saliormoon** [comment]
Yes, must it add any mirror or url in the setting.xml?

**Comment by mpv1989** [comment]
Usually not. But maybe it includes something that leads to conflicts. Can you post the content of the setting.xml?

**Comment by saliormoon** [comment]
OK. It doesn't has too many things, just like this:

<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <localRepository>D:\DATA\MAVEN</localRepository>

  <mirrors>
     <mirror>
			<id>big</id>
			<mirrorOf>*</mirrorOf>
			<name>data</name>			
            <url>http://10.175.102.184:8081/nexus/content/groups/public/</url>
		</mirror>
  </mirrors>
</settings>

**Comment by saliormoon** [comment]
Thank you very much. It is very kind of you to help me.

**Comment by bleac** [comment]
@saliormoon Hi! And how you resolved it?

**Comment by Mdd2017** [comment]
@saliormoon how did you resolve this? Thanks!

**Comment by tmtanzeel** [comment]
> Thank you very much. It is very kind of you to help me. I have resolved it.

How ??? I'm facing the same issue. Please share the solution.
