### ISSUE TITLE
[question] maxConnections parameter for 7.x.x arango client greater than 1

### ISSUE THREAD

**Issue by metroniko** [arangodb/arangodb-java-driver#531]
Hi everyone
According to the documentation https://docs.arangodb.com/3.11/develop/drivers/java/reference-version-7/driver-setup/, 7.x.x arango driver has maxConnections value 1 for HTTP2_JSON protocol 

Please tell me, what the behavior will be if the maxConnections property is set to a value greater than 1?

Does maxConnections affect performance in the case of HTTP2_JSON protocol?

**Comment by rashtao** [comment]
Thanks to HTTP/2 multiplexing, 1 connection should already offer good performances. In case it's needed, this value can be overridden explicitly configuring it with the desired number of max connections.

**Comment by rashtao** [comment]
Closing as inactive, please reopen if still relevant.
