### ISSUE TITLE
Because now my ArangoDB version is 3.0.5 ,  can I add version group 3.0.5 to the dependency of pom.xml?

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb-java-driver#54]
Because now my ArangoDB version is 3.0.5 ,  can I add version group 3.0.5 to the dependency of pom.xml? 

Any help is highly appreciated.

**Comment by mpv1989** [comment]
The last version of the java-driver is 3.0.3 (see [here](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.arangodb%22%20AND%20a%3A%22arangodb-java-driver%22)), there is no need of updating your pom if you do not update your driver version.

Beside that I highly suggest you to update your ArangoDB to our last release 3.0.10

**Comment by saliormoon** [comment]
Ok, thanks a lot

**Comment by mpv1989** [comment]
use zypper to upgrade to the latest version

**Comment by saliormoon** [comment]
Ok, could it be installed by overriding ? Or we must intsall the latest version after uninstallation?
