### ISSUE TITLE
"ArangoCollectionarangoDriver" can't be found in the arangodb-java-driver-3.0.3.

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb-java-driver#55]
"ArangoCollectionarangoDriver" can't be found in the arangodb-java-driver-3.0.3. 

Any help is highly appreciated .

**Comment by mpv1989** [comment]
That's right. There is no class called `ArangoCollectionarangoDriver`. May be you mean `ArangoDriver`?

I highly suggest you to take a look into your [Java tutorial](https://www.arangodb.com/tutorials/tutorial-java-old/)

**Comment by saliormoon** [comment]
Ok,thanks very much.
