### ISSUE TITLE
Field to create document.[1210] cannot create document, unique constraint violated

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb-java-driver#56]
Enviroments:
 ArangoDB (3.0.5)
Arangodb-java-driver-3.0.3

When I create a document with the code below:

   ArangoConfigure configure = new ArangoConfigure();
      ArangoDriver arangoDriver = new ArangoDriver(configure);
      String collectionName="firstcollection";
     try{
           CollectionEntity myArangoCollection=arangoDriver.createCollection(collectionName);
     }catch (Exception e){
            System.out.println("Failed to collection"+ collectionName+";"+e.getMessage());
        }
        BaseDocument myObject=new BaseDocument();
        myObject.setDocumentKey("myKey");
        myObject.addAttribute("a","Foo");
        myObject.addAttribute("b",42);
        try {
            arangoDriver.createDocument(collectionName,myObject);
            System.out.println("Document created");
        }catch (ArangoException e){
            System.out.println("Field to create document."+e.getMessage());
        }

It has a error:
Field to create document.[1210] cannot create document, unique constraint violated.

Any suggestion is appreciated greatly.

**Comment by mpv1989** [comment]
You can find a list of error-codes [here](https://docs.arangodb.com/3.0/Manual/Appendix/ErrorCodes.html)

**Comment by saliormoon** [comment]
Ok, it is resolved.Thanks a lot.
