### ISSUE TITLE
"executeQueryWithResultSet" can't be used in Arangodb-driver-3.0.3

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb-java-driver#57]
When I code like this:
 CursorResult rs=arangoDriver.executeQueryWithResultSet(query,bindVars2,BaseDocument.class,true,20);

the color of "executeQueryWithResultSet" is red. And it throws a error below:
"
Error:(105, 41) java: 找不到符号
  符号:   方法 executeQueryWithResultSet(java.lang.String,java.util.Map<java.lang.String,java.lang.Object>,java.lang.Class<com.arangodb.entity.BaseDocument>,boolean,int)
  位置: 类型为com.arangodb.ArangoDriver的变量 arangoDriver
"
Any suggestion is appreciated greatly.

**Comment by mpv1989** [comment]
The method `executeQueryWithResultSet` does not exist anymore. Use `executeDocumentQuery` or `executeAqlQuery` instead.

You can find the actual (and working) code of our tutorial [here](https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/example/FirstProject.java)

**Comment by saliormoon** [comment]
Ok, thanks a lot.
