### ISSUE TITLE
Simplify the query execution API

### ISSUE THREAD

**Issue by antonsarov** [arangodb/arangodb-java-driver#58]
Just by looking at the query execution API provided by the java driver, there is no easy way to tell which method is to be used to execute a standard AQL query:

![arangoexecutequeryapi](https://cloud.githubusercontent.com/assets/5653996/19418467/c34580cc-93c4-11e6-9a51-f8dff28d615c.png)

Even if I do not consider the deprecated methods (not on the picture) and the methods for Edge query and Vertext Query, there is still a bit of confusion there.

[This](https://gist.github.com/anonymous/bd68b523647548e5fb36d27c29561cfe) helps a little bit but still does not cover all the available options. Stuff like `executeAqlQueryJSON` returning `String` and `executeAqlQueryRaw` returning a `CursorRawResult` which includes JSON strings make the whole thing even worse.

So, my question are:

1. Are there any plans to simplify the API?
2. Can somebody point to an example showing the usage of the different methods?

**Comment by mpv1989** [comment]
1. Yes. We are actually working on a new driver verson with a complete new API and other features, which we will release with ArangoDB 3.1 (maybe by the end of this week). The new version will only contain one API call for executing AQL which is similar to the acutal `executeAqlQuery(String, Map<String, Object>, AqlQueryOptions, Class<T>)`.
2. I highly suggest you to only work with `executeAqlQuery` which actual works with POJOs, Map, List. This should be everything that you need. When you query for a vertices or edges, you should use a POJO that represents the vertex/edge document.

**Comment by antonsarov** [comment]
That is really good news. Thanks for the suggestion, I hope then this would make the migration to a newer driver version easier.

**Comment by miguel-porto** [comment]
Hi,
I'm now migrating my application to the new java API and it's great, much more intuitive and simple! However... we lost the ability to get the plain JSON response from the server, without processing. Sometimes all we need is to pass thru the JSON directly to the client, so, processing the JSON into Java objects and back into JSON is unnecessary burden. Are you thinking to allow this in the future (or willing to accept a PR on this), or should I make some workaround in my app?
Best, and congrats for the excellent job on the new API!

**Comment by mpv1989** [comment]
The new driver also supports plain Json results. Just use `String` as type for the result to get Json. This works on every API call (getDocument(), query(), ...).

You can find this in the documentation [here](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/basic_operations.md#read-document-as-json) and an example [here](https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/example/document/GetDocumentExample.java).

**Comment by miguel-porto** [comment]
Oops, sorry for not having seen this! Thanks for answering.
