### ISSUE TITLE
When there is no need to add orphanCollections, how can we create graph?

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb-java-driver#59]
Referring to https://github.com/arangodb/arangodb-java-driver

When there is no need to add orphanCollections, I code like this:

GraphEntity graph=driverDB.createGraph("test_Graph",edgeDefinitions,null,true);
 
But it throws a error:

om.arangodb.ArangoException: [1923] malformed edge definition
	at com.arangodb.BaseArangoDriver.checkServerErrors(BaseArangoDriver.java:191)
	at com.arangodb.BaseArangoDriver.createEntity(BaseArangoDriver.java:231)
	at com.arangodb.BaseArangoDriver.createEntity(BaseArangoDriver.java:306)
	at com.arangodb.impl.InternalGraphDriverImpl.createGraph(InternalGraphDriverImpl.java:86)
	at com.arangodb.ArangoDriver.createGraph(ArangoDriver.java:3550)
	at MyGraph.main(MyGraph.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Any suggestion  is greatly appreciated.

**Comment by weinberger** [comment]
Hi saliormoon,

you can find the explanation for this in the docs (https://docs.arangodb.com/3.0/Manual/Appendix/ErrorCodes.html).

"1923 - ERROR_GRAPH_CREATE_MALFORMED_EDGE_DEFINITION
the edge definition is malformed. It has to be an array of objects.,"

You can find more details at https://docs.arangodb.com/3.0/HTTP/Gharial/Management.html#create-a-graph

I would you very thankful if you would have a look at our docs. We put a lot effort into it and I think it's not so bad at all. If you find things which could be improved we are more than happy to appect PRs.

**Comment by saliormoon** [comment]
Hello, dear weinberger ,

Thanks for giving me your suggestion. I really appreciate it so much.
And also, I'm very sorry to hear you said  like this. 
As a newer, maybe I'm ridiculous to have asked these questions and not politely to say what as below. But I hope you can understand me correctly. 
That I ask something do not represent I consider the docs are not clear, but I just want to solve the problem more quickly. 
And I will accept your suggestion and have more consideration before asking. And I will continue to ask and to learn.

**Comment by saliormoon** [comment]
Hello, dear weinberger,

Thanks for giving me your suggestion. I really appreciate it so much.

And also, I'm very sorry to hear you said like this. 
As a newer, maybe I'm ridiculous to have asked these questions and not politely to say what as below. But I hope you can understand me correctly. 
That I ask something do not represent I consider the docs are not clear, but I just want to solve the problem more quickly. 
And I will accept your suggestion and have more consideration before asking. Thanks.

**Comment by weinberger** [comment]
I'm sorry if I wasn't polite. 

You should keep in mind that Arango is an open source project and we are happy to help our community but that can't mean that we speedup your development for free. The free support can't be a substitute for reading the documentation. 

Sent from iPhone, excuse typos

**Comment by saliormoon** [comment]
Well, I see, thank you.

**Comment by saliormoon** [comment]
Thank you for your help, weinberger.
