### ISSUE TITLE
no way to create edges outside graph context

### ISSUE THREAD

**Issue by normunds** [arangodb/arangodb-java-driver#6]
There us method to create edges directly in edge collection (version 2.5.0). Can only use corresponding graph method.

**Comment by gschwab** [comment]
I added a method to create edges outside a graph context.
driver.createEdge(...);

I hope this meets your needs

Will be released with the next driver version (very soon)

**Comment by gschwab** [comment]
fixed with 2.4.4 and 2.5.1
