### ISSUE TITLE
ArangoHost#toString() should return a human-readable representation in the form host:port

### ISSUE THREAD

**Issue by antonsarov** [arangodb/arangodb-java-driver#63]
Branches `2.7`, `3.0` and `3.1` use the `ArangoHost` class which includes a host and a port. There is an agreed-upon human-readable representation in the form "host:port". This is also defined in [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt). The `toString()` method should rely on this.

**Comment by mpv1989** [comment]
Pull request accepted in branch 3.1. Commit also merged in branch 2.7 and 3.0.
Changes will be in the next bugfix release.

Thanks a lot
Mark
