### ISSUE TITLE
arango db driver 3.1.x & Replication

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#67]
This is perhaps not an issue but me not knowing the API well as I am new to ArangoDB.  Using the driver version 3.1.x  I noticed there isn't a way to configure the number of shards & replication when using the ArangoDriver.createGraph API. 

Instead I have to use the ArangoDriver,createCollection and specify the CollectionOptions with the number of shards.  I would expect the replication factor to be available in this class but it is not.  Is there a way to change the replication factor using the java API?  If so, where is it located?

Currently setup is a 3 node cluster using the lateset version of ArangoDB each node running agency, primaryDB and coordinator.

**Comment by mpv1989** [comment]
At the current state of development there is no possibility of setting the number of shards or the replication factor by creating a graph. The driver talks with the http API of the server and it does not support it at the moment. You did right by creating the collections before creating the graph.

The missing replication factor in the options of `createCollection` is a bug. I will add it and release a bugfix-release within the next days.

Best,
Mark

**Comment by mpv1989** [comment]
The bug-fix release **4.1.1** and **3.1.3** is out.

**Comment by aznwarmonkey** [comment]
I just tired to use the new replication factor by calling `collectionOptions.setReplicationFactor(3);`
From the web UI,  under the collection information, the replication factor is still set to 1.  Is there something I am missing?  

The current version of Arango cluster I am running is 3.0.10.  I originally thought it was 3.1 but was mistaken.  Could this be the issue?

**Comment by aznwarmonkey** [comment]
I dug deeper into the source code and found that the replication factor is set but is never called.  See the attached snippet of code that is making the HTTP request

`/**
 * @author tamtam180 - kirscheless at gmail.com
 *
 */
public class InternalCollectionDriverImpl extends BaseArangoDriverImpl
		implements com.arangodb.InternalCollectionDriver {

	private static final String API_COLLECTION = "/_api/collection";

	InternalCollectionDriverImpl(ArangoConfigure configure, HttpManager httpManager) {
		super(configure, httpManager);
	}

	@Override
	public CollectionEntity createCollection(String database, String name, CollectionOptions collectionOptions)
			throws ArangoException {
		CollectionOptions tmpCollectionOptions = collectionOptions;
		if (tmpCollectionOptions == null) {
			tmpCollectionOptions = new CollectionOptions();
		}
		HttpResponseEntity res = httpManager.doPost(createEndpointUrl(database, API_COLLECTION), null,
			EntityFactory.toJsonString(
				new MapBuilder().put("name", name).put("waitForSync", tmpCollectionOptions.getWaitForSync())
						.put("doCompact", tmpCollectionOptions.getDoCompact())
						.put("journalSize", tmpCollectionOptions.getJournalSize())
						.put("isSystem", tmpCollectionOptions.getIsSystem())
						.put("isVolatile", tmpCollectionOptions.getIsVolatile())
						.put("keyOptions", tmpCollectionOptions.getKeyOptions())
						.put("numberOfShards", tmpCollectionOptions.getNumberOfShards())
						.put("shardKeys", tmpCollectionOptions.getShardKeys())
						.put("type", tmpCollectionOptions.getType() == null ? null
								: tmpCollectionOptions.getType().getType())
						.get()));

		return createEntity(res, CollectionEntity.class);

	}`

**Comment by mpv1989** [comment]
Yes. I found it too. I must have overlooked it. I fix it and release a new version (3.1.4).

Apart from this you should think about updating your ArangoDB to 3.1. The Java driver in version 3.1.x is not 100% compatible with ArangoDB 3.0.
