### ISSUE TITLE
GraphEntity name field is always null

### ISSUE THREAD

**Issue by schrock** [arangodb/arangodb-java-driver#72]
Using ArangoDB 3.1.0 and Java Driver 4.1.0:

If you get a collection of GraphEntity objects via ArangoDatabase.getGraphs(), the name field of returned GraphEntity objects will be null. I think this is due to the underlying API at /_api/gharial using "_key" instead of "name" to contain the graph name. The [official documentation](https://docs.arangodb.com/3.1/HTTP/Gharial/Management.html) specifies "_key" in some examples and "name" in others.

This can be fixed by simply adding a "_key" field and corresponding "get_key()" method in the GraphEntity class.

**Comment by mpv1989** [comment]
Fixed.
Still use `getName()` which leats to `name` or `key`, because only one exists at a time.

**Comment by schrock** [comment]
Thanks!
