### ISSUE TITLE
Implement bulk import API

### ISSUE THREAD

**Issue by gauravkumar37** [arangodb/arangodb-java-driver#76]
Old version of the driver v2.x has a bulk import API but the new ones do not.
Please implement the bulk import API https://docs.arangodb.com/3.1/HTTP/BulkImports/index.html

**Comment by mpv1989** [comment]
Hi,

I have not implemented it yet because with version 4.1.x we extends the document API with multi document operations. You can insert multiple documents with `ArangoCollection#insertDocuments(Collection<T>)`.
If this is not enough I can implement the bulk umport API within this week.

Best,
Mark

**Comment by gauravkumar37** [comment]
Hi,

Thanks for the update.
I need an API which allows me to insert multiple documents in 1 go. The behavior should be to create the documents if they don't already exist. If they do exist, whether to update them or to replace them should be passed via a flag.
Current APIs for multi document insert fail if documents already exist. Multi document replace fail if they don't exist.
Earlier, bulk API allowed me to do that.

Thanks,
GK

**Comment by mpv1989** [comment]
import API implemented in version 4.1.3

Note:
`ArangoCollection#importDocuments(Collection<?>,DocumentImportOptions)` works fine.

`ArangoCollection#importDocuments(String, DocumentImportOptions )` for raw Json import currently works only with JSON array and not with line separated JSON object. Also importByHeaderValues is not implemented yet. These features require a change in VelocyStream which is planned for a future server release.

**Comment by gauravkumar37** [comment]
Thanks @mpv1989, will test and report back.
