### ISSUE TITLE
Feature: VPack deserializer to handle enum constant not found (or "sometimes enums change...")

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb-java-driver#77]
Hi, I've come across this situation, which is somewhat inconvenient: I've got data stored with enum fields, but in my program I changed the enum constant names, so now I get the IllegalArgumentException when conducting a query. The problem is that it's worthless to catch this exception, as I can do nothing about it to correct the problem smoothly (given it hapens during the cursor of a query()).
There could be some way to tell the deserializer to assign a given enum value (or at least set to null) if the enum constant is not found. But I really don't know what would be the best approach. The exception is thrown [deep in the code](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/velocypack/VPack.java#L371), so there's no elegant way to pass custom info so deep... my suggestion is that the exception is caught in that line and the field is set to null. Then, after the query cursor finishes, the user may check for null values and assign whatever value he wants.
What do you think?

**Comment by mpv1989** [comment]
Hi,

there is already a mechanism for your case. You can register a custom `VPackDeserializer` for your enum over `ArangoDB.Builder#registerDeserializer(Class,VPackDeserialiser)`. In this deserializer you can catch the `IllegalArgumentException` and set the field to null or to a value depending on the string value in the VPack (little docu [here](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/serialization.md#custom-de-serializer)).

Your code could look like this:
```
VPackDeserializer<MyEnum> deserializer = new VPackDeserializer<EnumTest.MyEnum>() {
  @Override
  public MyEnum deserialize(VPackSlice parent, VPackSlice vpack, VPackDeserializationContext context)
      throws VPackException {
    try {
      return MyEnum.valueOf(vpack.getAsString());
    } catch (IllegalArgumentException e) {
      return null;
    }
  }
};

arangoDB = new ArangoDB.Builder().registerDeserializer(MyEnum.class, deserializer).build();
```

Let me know if this does not resolve your problem or if you think the solution is not comfortable enough.

Best,
Mark

**Comment by miguel-porto** [comment]
Oops, sorry again, should have found this solution before commenting! Yes, that looks like a perfect solution, will try it. Thank you for the patience. Next time I'll do the "homework" better before posting!
Best
Miguel
