### ISSUE TITLE
Automatic serializer/de-serializer for java.util.UUID

### ISSUE THREAD

**Issue by andekaputra** [arangodb/arangodb-java-driver#79]
Can we add serializer/de-serializer for java.util.UUID type?

**Comment by mpv1989** [comment]
I implemented serializer/de-serializer for java.util.UUID in version 4.1.4.

Best
Mark

**Comment by hooph00p** [comment]
@mpv1989 I'm seeing a similar issue with `java.time.Instant` serialization/deserialization. Can you point me to where the change was made? I'd like to see if this is something I could fix.
