### ISSUE TITLE
How to specify fallback hosts for new driver

### ISSUE THREAD

**Issue by atharva-infiverve** [arangodb/arangodb-java-driver#81]
Hi,

I am migrating the old v3 driver to new 4.1.0 driver. I am not able to find the method to add fallback hosts. I was able to do this in the old driver. Is there any new way to do that? or Arangodb automatically detects that?

Thanks & Regards,
Atharva

**Comment by mpv1989** [comment]
Hi Atharva,

there is currently no way for adding fallback hosts in the new driver. I will discuss this with my colleagues.

Best
Mark

**Comment by normanuber** [comment]
Any thing on this?

**Comment by mpv1989** [comment]
I will discuss this next week with my colleagues, whether this should be handled by our drivers or whether we should offer this functionality separately.

**Comment by normanuber** [comment]
Sure, if it could be asked for any reasons to be against this. It is odd that it is supported in an older version for reliability of the client then removed for unspecified reasons. I'm still on an older version and will stay with it until this is addressed. I hope this will be supported in an official capacity even though I will be doing my own wrapper.

**Comment by normanuber** [comment]
Actually, you know, a better solution would be to use a proxy within your own app for situations like this, so your app connects to that proxy. Proxy can be internal to the app or external.

**Comment by mpv1989** [comment]
@atharva-infiverve @normanuber I added support for multiple hosts in `4.1.9-SNAPSHOT`. It will be included in version `4.1.10` which will be released within the next week.

You can define as many hosts as you want with the method `host(String, int)` of the class `ArangoDB.Builder`. The methods `host(String)` and `port(int)` are deprecated and will be removed in a future release. You can also define multiple hosts over `arangodb.properties` with `arangodb.hosts=ip:port,ip:port`.

The current mechanism tries to connect to the first given host, if this fails it will be iterate over the hosts and repeat connecting until it succeed or all hosts failed.

We plan to expand this feature in the future with:
- option to connect to a random host from the list (for load balancing in multi-thread environments)
- support for host lists provided by a coordinator
- support for load balancing informations provided by a coordinator

**Comment by normanuber** [comment]
Oh wow, thanks for addressing this. I had made my own wrapper (with support for connection pooling provided by the apache commons pool) to handle this a few days ago, so I could make the upgrade to 4.1.

**Comment by mpv1989** [comment]
released version `4.1.10`
