### ISSUE TITLE
Does exist  any interface for create a database if not exist, and create a collection if not exist?

### ISSUE THREAD

**Issue by brucejee** [arangodb/arangodb-java-driver#83]
## I need write check code when create a database and a collection as follows:
        if (!arangoDB.getDatabases().contains(DB_NAME)) {
	        arangoDB.createDatabase(DB_NAME);
        }

        try {
	        database.collection(ENTITY_COLLECTION).getInfo();
        } catch (ArangoDBException e) {
	        if (e.getMessage().contains("Response: 404")) {
	            final CollectionCreateOptions collectionOpt = new CollectionCreateOptions();
	            collectionOpt.numberOfShards(10);
	            collectionOpt.type(CollectionType.DOCUMENT);
	            database.createCollection(ENTITY_COLLECTION, collectionOpt);
	        } else {
	            e.printStackTrace();
	        }
	    }
Is there any interface can do this just one call?

**Comment by mpv1989** [comment]
Hi,

there is no createIfNotExist for database or collection. The only you can do this with only one request is create the database/collection and catch the excpetion when it already exists.

```java
try {
  arangoDB.createDatabase(DB_NAME);
} catch (final ArangoDBException e) {
  // ignore if Response: 409, Error: 1207 - duplicate name
  if (!e.getMessage().equals("Response: 409, Error: 1207 - duplicate name")) {
    e.printStackTrace();
  }
}
```

**Comment by brucejee** [comment]
Thanks @mpv1989.  Will add createIfNotExist interface in the future?

**Comment by mpv1989** [comment]
I have written it on my todo-list for future discussions. I cannot guarantee it.

**Comment by brucejee** [comment]
Thanks, i got it.
