### ISSUE TITLE
Suggestion: use transient to mark fields not for serialization

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb-java-driver#86]
Hi, I would find the use of `transient` convenient (in addition to the annotation `@Expose`) to mark fields that are not meant to be serialized.
The reason is that I may want to have a JavaBean for multiple purposes (e.g. I may want to serialize it with Gson also), and it would be more convenient if all the serializers I may use understand the same keyword `transient` equally. Moreover, it would be more convenient not to have to import `com.arangodb` in the JavaBean because I may want to have a JavaBean that lives seperately, independent of the underlying DB, for example.
What do you think?
Cheers,

**Comment by mpv1989** [comment]
Hi,
thank you for your ideas. I wanted to optimize this part already longer.
I have implemented it now that you can register an annotation to filter or name fields within the de-/serialization process. You can test this with version 4.1.5-SNAPSHOT. I will release version 4.1.5 within this week. If you have any improvement suggestions please let me know.

In `ArangoDB.Builder` you will find the methods `annotationFieldFilter` and `annotationFieldNaming` with which you can add your annotations and their logic for serialize, deserialize and serialized-name:

    ArangoDB arangoDB = new ArangoDB.Builder()
        .annotationFieldFilter(Transient.class, new VPackAnnotationFieldFilter<Transient>() {
          @Override
          public boolean serialize(final Transient annotation) {
            return true;
          }

          @Override
          public boolean deserialize(final Transient annotation) {
            return true;
          }
        }).build();

Thanks & Best
Mark

**Comment by miguel-porto** [comment]
I see - this way I can pass the annotation logic to my package only, thus making it independent of the DB. My suggestion, originally, was about using the java's `transient` field qualifier (not annotation) for this purpose, but your solution is ok anyway!
Thanks, all the best
Miguel

**Comment by mpv1989** [comment]
Ohh, I have misunderstood you. I had not even thought of that.
I have it implemented yet.

Thanks!
Best
Mark

**Comment by miguel-porto** [comment]
It was just a suggestion, don't take it too seriously if you don't think it's useful!
Thanks!
Miguel

**Comment by mpv1989** [comment]
I think it's useful, I just did not think about it before.
