### ISSUE TITLE
NullPointerException serializing array with null element

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb-java-driver#88]
Hi,
It seems it is not possible to update a document with a bean with an array field with null element, like `somefield: [3, null]`, it throws a NPE!
However, I can do it in AQL, so it's perfectly legal.
Cheers.
Miguel

**Comment by mpv1989** [comment]
Hi,
will be fixed in version 4.1.5 which I will release within this week. You can already use it with 4.1.5-SNAPSHOT.

Thanks & Best
Mark

**Comment by miguel-porto** [comment]
Thanks!
But I can see in the committed code that null array elements now are dropped. This is not consistent with what happens if I do it in AQL, i.e., the array will be saved keeping the null elements, like [3, null]. Is this the desired behavior? IMO null elements should be kept for consistency reasons (e.g. keeping the same array size).
Best,
Miguel

**Comment by miguel-porto** [comment]
Imagine, for example, my array can represent the bars of a bar plot, and null may mean "no data", which is not the same as zero; yet, the space for the bar must be there anyway.

**Comment by mpv1989** [comment]
You are totally right. I changed it.

Thanks & Best
Mark

**Comment by miguel-porto** [comment]
Looks perfect now; thanks!
Best,
Miguel
