### ISSUE TITLE
Traversal support

### ISSUE THREAD

**Issue by mrbatista** [arangodb/arangodb-java-driver#9]
Could you confirm that driver does not support traversal API?

**Comment by a-brandt** [comment]
Yes. The traversal API is missing in the driver.

**Comment by mrbatista** [comment]
There is in planning the implementation of this feature?

**Comment by a-brandt** [comment]
We will implement the traversal API in the next months.

**Comment by a-brandt** [comment]
I added the traversal API (see ArangoDriverTraversalTest.java)
