### ISSUE TITLE
I'd like to contribute a custom recursive deserializer/serializer VPackSlice <-> Jackson ObjectNode

### ISSUE THREAD

**Issue by sheinbergon** [arangodb/arangodb-java-driver#90]
Would it be of any interest to you? If so, where would you like me to add it ( as part of a pull request )

**Comment by mpv1989** [comment]
Hi,
thanks a lot for your contribution. In general I like the idea to offer support for jackson but I would like to keep the basic driver as free as possible from additional dependencies or requirements.
But we are currently playing with the thought of offering various optional extensions for the driver, like support of Java8 types (Instant, LocalDate, ...) or better support of Scala types (nested Collections/Maps).
These extensions would be interesting for people whose setting involves more than just Java 6.
Your idea would fit very well into one of these extensions. I will discuss this with my colleagues and report back.

Thanks & Best
Mark

**Comment by sheinbergon** [comment]
@mpv1989  You can do still keep your dependencies to a minimum by making the jackson dependencies run-time/provided only and making the decision if to jackson-support is even activated up to the user .

Another alternative  is to make the de/serialization functionality into to some sort of  "SPI" where the current Pojo support is one ( default) implementation and Jackson is another optional one.

Let me know what you think ( I might consider creating a pull request )

**Comment by mpv1989** [comment]
@sheinbergon The idea with jackson as a provided dependency sounds most sensible to me.

It could be realised easely by register `VPackSerializer<ObjectNode>` and `VPackDeserializer<ObjectNode>` on `VPack.Builder` in the class `VPackConfigure`. You can take a look [here](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/serialization.md#custom-de-serializer) for more information. We would be very happy about a pull request from you. Let me know if I can provide you any help.

Thanks a lot
Mark

**Comment by sheinbergon** [comment]
@mpv1989  as of the ObjectNode support - I agree with your suggestion. ( regarding the link - well yeah, that's how I implemented it  ) 

Just to make sure we're on the same page, what is exactly you would like to see in the PR ? I think we should aim to add fully fledged Jackson support, just make it optional via dependency-scopes and configuration settings

**Comment by mpv1989** [comment]
@sheinbergon full Jackson support sounds good. Depenency-scope `provided` should be used. On what other configuration settings do you thought?

**Comment by sheinbergon** [comment]
a configuration property to enable jackson, so dynamic classloading won't even be attempted in case jackson is not explicitly enabled

**Comment by mpv1989** [comment]
ahh ok, sure :-)

**Comment by sheinbergon** [comment]
I'm guessing these would be a good place to start 

https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/velocypack/VPack.java

https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/velocypack/VPackAnnotationFieldFilter.java

https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/velocypack/VPackAnnotationFieldNaming.java

**Comment by sheinbergon** [comment]
@mpv1989  funny enough, I believe the correct approach for adding jackson support would actually be to customize jackson ( register custom module for jackson ) to serialize everything into VPackSlice.

Once we have VPack, it'll be easier to integrate into the current serialization flow, as I'm assuming you already support it :).

**Comment by mpv1989** [comment]
Yes you can code against the master branch.

I would try to start in [VPackConfigure](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/internal/velocypack/VPackConfigure.java) and register a `VPackSerializer` and `VPackDeserializer` for every Jackson Entity like ObjectNode. In this class you can also register custom `VPackAnnotationFieldFilter` and probably everything else that you need.

**Comment by sheinbergon** [comment]
@mpv1989 That was my first approach, but unfortunately, that's not what jackson is about.
Jackson is all about annotations. Trying to support all of them via the arango driver will be a hugh effort and will require too many customiations. See my suggestion above  in  #issuecomment-274845709

**Comment by mpv1989** [comment]
I am not very familiar with Jackson. Is there any mechanism which process the annotations and we can register a Handler in it, in which we simply build a VelocyPack?

**Comment by sheinbergon** [comment]
Let me have a deeper, thorough look at things and get back to you. It'll require some research

**Comment by sheinbergon** [comment]
@mpv1989  from what I can tell, ```VPackParser``` does ```VPackSlice``` <-> Json ```String```
What we want to achieve in order to adding jackson is equivalent to adding support for more annotations ( not that I'm intending to do so).

Anyway - the right course of action should be :

- Create a Jackson module ( Jackson is extensible for such needs )  that overrides all of the Jackson custom de/serializers with ```VPackBuilder``` aware implementations ( results will be saved into the builder instance ). 
- If Jackson is enabled, registered the above module to An Arango Dedicated ```ObjectMapper``` ( Jackson's main interface object )
- Use Jackson ```ObjectWriter```/```ObjectReader``` in order to pass the builder itself as a per-call attribute
- If Jackson is enabled  then use a Jackson ```ObjectMapper``` ( either default or injected externally ) to create the above ```ObjectWriter``` instance +  create a ```VPackBuilder``` instance and pass it to writer.
- commence the serialization via one of the ```ObjectWriter``` ```write*``` methods.
- Then call the ```slice()``` method. you will now have a valid VPackSlice of the POJO. and you can work with it from that point on 
- If Jackson is disabled ,serialize as usuall

**Comment by mpv1989** [comment]
@sheinbergon sorry for the late response. Your idea sounds solid.
If you don't have to touch much of the existing code, we can maybe implement the switch in [ArangoUtil](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/util/ArangoUtil.java) and not in `VPack`.

**Comment by sheinbergon** [comment]
@mpv1989 thanks for your affirmation. I've been away for the past week, so havn't gottem round to actually foing anything. Is the ```ArangoUtil``` class always  part of the de/serislization method call heirarchey ?

**Comment by mpv1989** [comment]
@sheinbergon `ArangoUtil` is a wrapper around the class `VPack` and `VPackParser` and is directly used from the driver api methods. We could implement the jackson parsing here and leave the original vpack parsing untouched or we write a VPackSerializer/VPackDeserializer and register them at `VPack.Builder` (if it is possible) and leave the original vpack parsing untouched too. We should definitely avoid touching the class `VPack`.

For my understanding. There is no class level annotation in jackson which is required? Can't find one  [here](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations). We could have used this to identify whether we switch to jackson->vpack parsing automatically.

Best
Mark

**Comment by sheinbergon** [comment]
Hi again @mpv1989.

I finally got to running some initial tests. It seems like my initial approach was indeed correct. 
I've created a simple Jackson module, that when serializing a bean consisting of a single boolean field and passing it a premade VPackBuilder, populates it properly ( including the handling of Jackson Annotations).

Next up, I just need to replicate all of the the Jackson De/Serializer implementations and make them VPack aware, which is probably going to be a tedious job.

I'll provide more updates soo enough, I hope

**Comment by sheinbergon** [comment]
@mpv1989 A Question regarding Deserialization.

I currently see know way to read from VPack -> POJO and pass it through jackson processor to support the various annotations.

However, if we do VPack -> Json -> POJO(Via Jackson)  it'll work, but it  means the de-serialization process  will be a tad slower. 

Will that be an acceptable solution from your POV?

10x

**Comment by mpv1989** [comment]
@sheinbergon sounds good. We should try this solution in the first step. I will later make some performance tests and optimization if needed.

Thanks & Best
Mark

**Comment by TiGz** [comment]
Any news on this or some kind of ETA? :0)

Many thanks,

Adam

**Comment by sheinbergon** [comment]
@TiGz  Sorry, I haven't gotten round to making any progress with this due to personal issues. Will finally have some time over the weekend. I'll keep all of you posted

**Comment by TiGz** [comment]
@sheinbergon hey no worries, thanks for letting me know!

**Comment by mpv1989** [comment]
@sheinbergon I changed a lot of stuff in the driver today.

* extracted VelocyPack implementation to https://github.com/arangodb/java-velocypack
* added support for replacing build-in VelocyPack serializer/deserializer

`ArangoDB.Builder` now has the methods `setSerializer(ArangoSerializer)` and `setDeserializer(ArangoDeserializer)`. With them you can completely replace the build-in  `VPack`/`VPackParser`. I think this is the best way to allow switching to Jackson. If I find some time next week I will take a look into the Jackson topic.

**Comment by sheinbergon** [comment]
@mpv1989  That sounds great Mark. based on our chat so far, I've decided to go on a simpler approach where the serialization process will also be POJO -> Json String(Via  Jackson) -> Vpack.

Hopefully I'll have some updates to share within the next few days

**Comment by sheinbergon** [comment]
@mpv1989 what's point of signatures like ```public <T> T deserialize(final VPackSlice vpack, final Type type) throws ArangoDBException``` ? your defining Generic T but not using it to bind the type. Why not change it to ```public <T> T deserialize(final VPackSlice vpack, final Class<T> type) throws ArangoDBException```?

**Comment by sheinbergon** [comment]
@mpv1989 Ok, I've done some more overviewing of the new code. I think it'd be best if we have a voice call/chat to clear up some of the issues. Let me know when you'd be available to do that.

**Comment by mpv1989** [comment]
@sheinbergon 
* which IDE: I use Eclipse. You can find my formatter configuration [here](https://github.com/arangodb/arangodb-java-driver/blob/master/formatter.xml)
* I use `Type` instead of `Class<T>` because of parameterised types. e.g. `Collection<MyEntity>`. The only way I know how you can specify this is by `new Type<Collection<MyEntity>>() {}.getType()` which is from type `Type`. I use this several times (e.g. [here](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/internal/InternalArangoDB.java#L214))

I looked at the jackson project at the weekend somewhat more closely. I would like to offer a jackson-modul independent of the driver like other jackson modules ([csv](https://github.com/FasterXML/jackson-dataformat-csv), [xml](https://github.com/FasterXML/jackson-dataformat-xml)). With the separate [velocypack implementation](https://github.com/arangodb/java-velocypack) I build last week, this should be possible. I created a new repo ([jackson-dataformat-velocypack](https://github.com/arangodb/jackson-dataformat-velocypack)) in which I was playing around a little bit. Maybe you can take a look at it and tell me what do you think. In the first step I was able to serialize/deserialize a very simple POJO (test [here](https://github.com/arangodb/jackson-dataformat-velocypack/blob/master/src/test/java/com/arangodb/jackson/dataformat/velocypack/SimpleTest.java)).
I also commited the class `VelocyJack` :stuck_out_tongue_winking_eye: to the driver, which is just an idea how we can optional integrate jackson.

For communication I would prefer our [community slack](https://slack.arangodb.com/) (my username is `mark.arangodb`).

**Comment by TiGz** [comment]
Just wondering where this got to? :0)

**Comment by sheinbergon** [comment]
I think @mpv1989  already implemented jackson support as  a separate module. I'm closing tihs

**Comment by mpv1989** [comment]
I started [here](https://github.com/arangodb/jackson-dataformat-velocypack) but didn't found time for it. I will continue working on it within the next 3 weeks.

**Comment by mpv1989** [comment]
@sheinbergon @TiGz I finally had some time to finish the implementation of the [jackson-dataformat-velocypack](https://github.com/arangodb/jackson-dataformat-velocypack).

With driver version 4.5.2 you are able to use jackson as an alternative serializer. Take a look into the [docs](https://github.com/arangodb/arangodb-java-driver/blob/master/docs/Drivers/Java/Reference/Serialization.md#use-of-jackson-as-an-alternative-serializer) to see how easily it is set up.
