### ISSUE TITLE
collection.insertDocuments not working for JSON strings

### ISSUE THREAD

**Issue by DanielPorter** [arangodb/arangodb-java-driver#91]
Working with the arangodb java driver trying to bulk insert documents, we're encountering that while the driver will allow us to insert a single document as a json string:

val js = ObjectToJson(obj).toString
db.collection.insertDocument(js)

it will not allow us to insert a set of documents as json string:
val js = ObjectToJson(obj).toString
val jsArray = new Array(js)
db.collection.insertDocuments(jsArray)

**Comment by mpv1989** [comment]
Thanks for reporting this bug. I fixed it in version 4.1.7

**Comment by DanielPorter** [comment]
Thanks!
