### ISSUE TITLE
Unable to create edges with replication, sharding, and syncing

### ISSUE THREAD

**Issue by DanielPorter** [arangodb/arangodb-java-driver#92]
When using the create shard commands to do our database setup, we don't see a way to pass options into the edge creation in the same way that you can for creating a collection - nor did we see a way to specify that a collection was an edge. Wondered if we're missing something, or if this isn't supported yet.

Thanks!

**Comment by neunhoef** [comment]
Are you referring to the process of creating an edge collection? Or are you creating edges in an already existing edge collection?

**Comment by DanielPorter** [comment]
Yes, I am referring to the creation of an edge collection, not an edge.

**Comment by mpv1989** [comment]
You can use the method `createCollection(String, CollectionCreateOptions)` for that.

```java
CollectionCreateOptions options = new CollectionCreateOptions()
        .type(CollectionType.EDGES)
        .numberOfShards(4)
        .shardKeys(new String[]{"key1","key2"})
        .replicationFactor(4)
        .waitForSync(true);
arangoDB.db().createCollection("myCollection", options);
```

**Comment by DanielPorter** [comment]
Ah, type was the thing we missed. Thanks for the direction.
