### ISSUE TITLE
Error while read long value

### ISSUE THREAD

**Issue by leejaku17** [arangodb/arangodb-java-driver#94]
Hi. 

I used Java Driver 3.x very well. But after I upgraded Java driver to 4.x, I faced some problems. Please help me. 

1. I can store long type value, but when I read them from arango database, exception raised named "com.arangodb.velocypack.exception.VPackValueTypeException: Expecting type INT or UINT or SMALLINT"

Data is stored as like this. 
`{"errwh":0,"ts":1485879900000,"wh":0,"when":"(non-representable type)"}`

But exceptions like this when reading. 
`[01:56:00] ERROR c.v.p.o.n.NaoPushMapper:405 com.arangodb.ArangoDBException: com.arangodb.velocypack.exception.VPackParserException: com.arangodb.velocypack.exception.VPackValueTypeException: Expecting type INT or UINT or SMALLINT
com.arangodb.ArangoDBException: com.arangodb.velocypack.exception.VPackParserException: com.arangodb.velocypack.exception.VPackValueTypeException: Expecting type INT or UINT or SMALLINT
	at com.arangodb.util.ArangoUtil.deserialize(ArangoUtil.java:72)
	at com.arangodb.internal.ArangoExecutor.deserialize(ArangoExecutor.java:112)
	at com.arangodb.internal.ArangoCursorIterator.next(ArangoCursorIterator.java:67)
	at com.arangodb.ArangoCursor.next(ArangoCursor.java:110)
	at com.voce.protoss.obixmap.naopush.NaoDatabase.queryDemandItems(NaoDatabase.java:200)
	at com.voce.protoss.obixmap.naopush.NaoPushMapper.invokeObix(NaoPushMapper.java:372)
	at com.voce.protoss.commport.CommPort.mainLoop(CommPort.java:204)
	at com.voce.protoss.commport.CommPort.run(CommPort.java:152)
Caused by: com.arangodb.velocypack.exception.VPackParserException: com.arangodb.velocypack.exception.VPackValueTypeException: Expecting type INT or UINT or SMALLINT
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:299)
	at com.arangodb.util.ArangoUtil.deserialize(ArangoUtil.java:68)
	... 7 common frames omitted
Caused by: com.arangodb.velocypack.exception.VPackValueTypeException: Expecting type INT or UINT or SMALLINT
	at com.arangodb.velocypack.VPackSlice.getAsNumber(VPackSlice.java:235)
	at com.arangodb.velocypack.VPackSlice.getAsLong(VPackSlice.java:241)
	at com.arangodb.velocypack.internal.VPackDeserializers$4.deserialize(VPackDeserializers.java:77)
	at com.arangodb.velocypack.internal.VPackDeserializers$4.deserialize(VPackDeserializers.java:71)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:408)
	at com.arangodb.velocypack.VPack.deserializeField(VPack.java:391)
	at com.arangodb.velocypack.VPack.deserializeFields(VPack.java:379)
	at com.arangodb.velocypack.VPack.deserializeObject(VPack.java:330)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:429)
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:297)
	... 8 common frames omitted
`

The code is... 

`public class NaoDemandItem {
    @DocumentField(Type.KEY)
    private String documentKey;
    
    @DocumentField(Type.ID)
    private String documentHandle;

    @DocumentField(Type.REV)
    private Long documentRevision;
    
    private Date when;  //NOTE: date type은 기록하지 못함 
    private long ts;    //NOTE: long은 32비트로 잘라서 기록하는 듯 . 
    private long wh;
    private double errwh;
    
    public NaoDemandItem() {
        
    }
    
    public NaoDemandItem(Date when, long wh) {
        this.setWhen(when);
        if (wh >= 0) {
            this.wh = wh;
        } else {
            this.errwh = (double)wh/1000.0;
            this.wh = 0;
        }
    }

    public String getDocumentHandle() {
        return documentHandle;
    }

    public void setDocumentHandle(String documentHandle) {
        this.documentHandle = documentHandle;
    }

    public String getDocumentKey() {
        return documentKey;
    }

    public void setDocumentKey(String documentKey) {
        this.documentKey = documentKey;
    }

    public Long getDocumentRevision() {
        return documentRevision;
    }

    public void setDocumentRevision(Long documentRevision) {
        this.documentRevision = documentRevision;
    }

    public Date getWhen() {
        return when;
    }

    public void setWhen(Date when) {
        this.when = when;
        SimpleDateFormat keysdf = new SimpleDateFormat("yyyyMMdd'T'HHmmss");
        this.documentKey = keysdf.format(when);
        this.ts = when.getTime();
    }

    public long getWh() {
        return wh;
    }

    public void setWh(long wh) {
        this.wh = wh;
    }

    public long getTs() {
        return ts;
    }

    public void setTs(long ts) {
        this.ts = ts;
    }

    public double getErrwh() {
        return errwh;
    }

    public void setErrwh(double errwh) {
        this.errwh = errwh;
    }
    
    @Override
    public String toString() {
        return String.format("NaoDemandItem{ _key=%s, handle=%s, when=%s, wh=%d, errwh=%g, ts=%d", documentKey, documentHandle, when, wh, errwh, ts);
    }
}`

and ...

`public List<NaoDemandItem> queryDemandItems(int addr, Date start, Date end, long limit) throws Exception {
        String collname = this.readDevice(addr, "histories");
        if (collname == null) {
            return null;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        String query = 
                "FOR d IN @@coll " + 
                "FILTER d.ts >= DATE_TIMESTAMP(@from) && d.ts < DATE_TIMESTAMP(@to) " +
                "SORT d.ts ASC " +
                "LIMIT @lim " +
                "RETURN d";
        Map<String,Object> binds = new MapBuilder()
                .put("@coll", collname)
                .put("from", sdf.format(start))
                .put("to", sdf.format(end))
                .put("lim", limit).get();      
        ArangoCursor<NaoDemandItem> cursor = this.db.query(query, binds, null, NaoDemandItem.class);
        
        List<NaoDemandItem> list = new ArrayList<NaoDemandItem>();
        while (cursor.hasNext()) {
            NaoDemandItem item = cursor.next();     // <== Exception raised from here !!!!
            list.add(item);
        }
        return list;
    }`

2. When I used java driver 3.x, Date type stored as ISO8601 format, like this. 

`{"errwh":0,"ts":1482976800000,"wh":16415,"when":"2016-12-29T11:00:00.000+0900"}`

But after I upgraded to 4.x, Date field is not representing like this. 

`{"errwh":0,"ts":1485879900000,"wh":0,"when":"(non-representable type)"}`

Please help me. I'm stucked with this issue.

**Comment by mpv1989** [comment]
Hi,

1. Since ArangoDB 3.0 the revision of documents includes non-numeric characters. So you have to use `String` as type for documentRevision.
```
@DocumentField(Type.REV)
private String documentRevision;
```

2. The Java driver serialize your Pojo to [VelocyPack](https://github.com/arangodb/velocypack/blob/master/VelocyPack.md). VelocyPack knows a date type which is used from the driver when serializing java.util.Date. This works fine if you only work with the Java driver but result in `(non-representable type)` when you work with Arango-Shell or the webUI. We are not happy with this situation and will change this in the driver in the next version which will be released within the next days. Then the driver will store java.util.Date as String in the DB. In the meantime you can use `String` instead of `Date` as a workaround.

Best
Mark

**Comment by leejaku17** [comment]
Thank you for reply. 
I found some work-around and my program is working good. But your advice give me some inspiration, so I have plan to make better way. 
Anyway when I have some time, I will make some unit test and verify it. 
Thank you very much.

**Comment by mpv1989** [comment]
released 4.1.8 today including the fix for java.util.Date
