### ISSUE TITLE
ArangoDBException enhancement 

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#95]
It would be good to enhance the ArangoDBException class to be able to get the error code.  

This will enable proper error handling based on response code. Currently I believe all of it is embedded in a String

**Comment by mpv1989** [comment]
Hi,

I implemented this for just a few hours. You can already test it with version `4.1.8-SNAPSHOT`. I will release a new version within this week.

Best
Mark

**Comment by christian-lechner** [comment]
Just wanted to ask for the same enhancement :+1:

**Comment by mpv1989** [comment]
implemented in version 4.1.8
