### ISSUE TITLE
insertDocuments Method enhancements or alternatives

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#96]
Looking at the API, the insertDocuments is a way to perform batch insertions efficiently?  

Currently, if i am not mistaken then if an error occurs it will fail immediately.  Is there a way enhance this method or have an alternative that if an error occurs it will continue to try to ingest the remaining elements in the collections and return return error codes for the ones it fails?

**Comment by mpv1989** [comment]
Hi,

to batch insert documents without breaking on one failed document you can use `importDocuments` instead. It uses the [import http api](https://docs.arangodb.com/3.1/HTTP/BulkImports/#imports-document-values).

Best
Mark
