### ISSUE TITLE
collection.updateDocuments ,collection. replaceDocuments not working for JSON strings

### ISSUE THREAD

**Issue by divyajana21** [arangodb/arangodb-java-driver#98]
Working with the arangodb java driver trying to do bulk operations, we're encountering that while the driver will allow us to update a single document as a json string (Key, Js string):
 
val js = ObjectToJson(obj).toString
db.collection.updateDocument(String,js)

it will not allow us to update a set of documents as Map(String,json string):
val js = ObjectToJson(obj).toString
db.collection.updateDocuments(Map(String,String))

Similarly, we are trying to do bulk operation on replaceDocuments 

It allows,
val js = ObjectToJson(obj).toString
db.collection.replaceDocument(String,js)
but not, 
db.collection.replaceDocuments(Map(String,String))

**Comment by mpv1989** [comment]
Hi,
the methods `updateDocuments`/`replaceDocuments` work with `Collection<String>` in the case of working with raw Json. You have to build the `_key` of the document - you want to update - in the document. (see [here ](https://github.com/arangodb/arangodb-java-driver/blob/deb102ba04a900b393a75d766dab6c9d00bace22/src/test/java/com/arangodb/ArangoCollectionTest.java#L1534) for example)

But beside that I find a bug in this methods, so thanks for reporting. I fixed it. You can test it with current snapshot version `4.1.8-SNAPSHOT`. I will release a new version (`4.1.8`) within this week.

Thanks & Best
Mark

**Comment by mpv1989** [comment]
fixed in version 4.1.8
