### ISSUE TITLE
Unable to create graph

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb-java-driver#99]
This is the following error message I am getting after I try to create a graph from the Java Driver

`Exception in thread "main" com.arangodb.ArangoDBException: Response: 400, Error: 1932 - collection _graphs does not exist
	at com.arangodb.internal.velocystream.Communication.checkError(Communication.java:104)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:120)
	at com.arangodb.internal.velocystream.CommunicationSync.execute(CommunicationSync.java:40)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58)
	at com.arangodb.ArangoDatabase.createGraph(ArangoDatabase.java:491)
	at main.CreateGraph.main(CreateGraph.java:91)`

This is the method I am using to create the graph:

`			final String graphName = "myGraph";
                        final List<EdgeDefinition> edgeDefinitions = addDefinitions();
                       database.createGraph(graphName, edgeDefinitions);
`

I also want to add that I tired running the example to create a graph from the project and it resulted in the same errors as well.  Any ideas on what seems to be the problem and how to address it?

**Comment by christian-lechner** [comment]
Maybe this helps: (https://github.com/arangodb/arangodb-java-driver/issues/87#issuecomment-270088178)

**Comment by mpv1989** [comment]
Hi,

the collection `_graphs` is a system collection where the graph informations are stored. It should always exist. Can you please check if it really does not exists? You can do so over the webUI (tab "collections" -> settings in the right top corner -> select type "system") or with the java driver `arangoDB.db().getCollections(new CollectionsReadOptions().excludeSystem(false))`. If it does not exists, please post all system collections you can see here (system collections starts with `_`).

Are you running a single server or a cluster?

**Comment by aznwarmonkey** [comment]
Thanks for the quick response.  I am currently running ArangoDB V3.1.8 in CLUSTER mode.
Seems like any of the data i created from the java driver is not visible through the webUI and arangoSH.  Perhaps it is related to this issue https://github.com/arangodb/arangodb-java-driver/issues/93

So what I did is i created a new database through the webUI and verified that that collection is indeed there.  


<img width="1767" alt="collections" src="https://cloud.githubusercontent.com/assets/4139275/22546513/68fc4672-e90b-11e6-9527-8de4230e6bfa.png">

However in code it is rather interesting.  Below is the list of collections that are available through code:
`_apps
s1241969
s1241971
s1241973
s1241978
s1241980
s1241982
s1241984
s1241986`

 I am still unable to create the graph in that database.  Any ideas to what is causing this discrepancy ?

**Comment by mpv1989** [comment]
In your output the shard ids and not the collection names are printed. This indicates that your config - for the java driver - includes the ip to one of your db servers and not to a coordinator. Be sure that your java program works against one of your coordinators.
`ArangoDB.Builder().host("<ip-to-coordinator>").build();`

**Comment by aznwarmonkey** [comment]
Thanks for the suggestion that worked!  I am still trying to find my way around Arango and whatnot appreciate the quick response
